/*******************************************************************************
* File Name: cycfg_capsense.h
* Version: 3.20
*
* Description:
* CapSense Middleware configuration
* This file should not be modified. It was automatically generated by
* CapSense Configurator 3.20.0.3518
*
********************************************************************************
* Copyright 2020 Cypress Semiconductor Corporation
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#if !defined(CYCFG_CAPSENSE_H)
#define CYCFG_CAPSENSE_H

#include <stddef.h>
#include "cy_device_headers.h"
#include "cycfg_peripherals.h"
#include "cycfg_routing.h"

#define CY_CAPSENSE_CFG_TOOL_VERSION              (320)

#if !defined(CY_DISABLE_CAPSENSE)

#if (CY_CAPSENSE_CORE == __CORTEX_M)


#if !defined(CY_MSC0_Cmod1_PORT) || !defined(CY_MSC0_Cmod1_PIN) || !defined(CY_MSC0_Cmod1_PORT_NUM)
#error CY_MSC0_Cmod1 Capacitor is not assigned: missing #define CY_MSC0_Cmod1_PORT, #define CY_MSC0_Cmod1_PIN, #define CY_MSC0_Cmod1_PORT_NUM
#endif

#if !defined(CY_MSC0_Cmod2_PORT) || !defined(CY_MSC0_Cmod2_PIN) || !defined(CY_MSC0_Cmod2_PORT_NUM)
#error CY_MSC0_Cmod2 Capacitor is not assigned: missing #define CY_MSC0_Cmod2_PORT, #define CY_MSC0_Cmod2_PIN, #define CY_MSC0_Cmod2_PORT_NUM
#endif

#if !defined(CY_MSC1_Cmod1_PORT) || !defined(CY_MSC1_Cmod1_PIN) || !defined(CY_MSC1_Cmod1_PORT_NUM)
#error CY_MSC1_Cmod1 Capacitor is not assigned: missing #define CY_MSC1_Cmod1_PORT, #define CY_MSC1_Cmod1_PIN, #define CY_MSC1_Cmod1_PORT_NUM
#endif

#if !defined(CY_MSC1_Cmod2_PORT) || !defined(CY_MSC1_Cmod2_PIN) || !defined(CY_MSC1_Cmod2_PORT_NUM)
#error CY_MSC1_Cmod2 Capacitor is not assigned: missing #define CY_MSC1_Cmod2_PORT, #define CY_MSC1_Cmod2_PIN, #define CY_MSC1_Cmod2_PORT_NUM
#endif

#if !defined(Button0_Rx0_PORT) || !defined(Button0_Rx0_PIN)
#error Button0_Rx0 Sensor is not assigned: missing #define Button0_Rx0_PORT, #define Button0_Rx0_PIN
#endif

#if !defined(Button0_Tx_PORT) || !defined(Button0_Tx_PIN)
#error Button0_Tx Sensor is not assigned: missing #define Button0_Tx_PORT, #define Button0_Tx_PIN
#endif

#if !defined(Button1_Tx_PORT) || !defined(Button1_Tx_PIN)
#error Button1_Tx Sensor is not assigned: missing #define Button1_Tx_PORT, #define Button1_Tx_PIN
#endif

#if !defined(CY_CAPSENSE_CPU_CLK)
#error CPU clock frequency is not set: missing #define CY_CAPSENSE_CPU_CLK
#endif

#if !defined(CY_CAPSENSE_PERI_CLK)
#error Peripheral clock core is not set: missing #define CY_CAPSENSE_PERI_CLK
#endif

#if !defined(CY_CAPSENSE_VDDA_MV)
#error VDDA voltage is not set: missing #define CY_CAPSENSE_VDDA_MV
#endif

#if !defined(CY_CAPSENSE_PERI_DIV_TYPE)
#error Peripheral clock divider type is not set: missing #define CY_CAPSENSE_PERI_DIV_TYPE
#endif

#if !defined(CY_CAPSENSE_PERI_DIV_INDEX)
#error Peripheral clock divider index is not set: missing #define CY_CAPSENSE_PERI_DIV_INDEX
#endif



#include "cy_capsense.h"

/* Supported CapSense Middleware version */
#define CY_CAPSENSE_MW_VERSION_REQUIRED           (200)

#if !defined (CY_CAPSENSE_MW_VERSION)
    #if (CY_CAPSENSE_MW_VERSION_MAJOR == 2)
        #define CY_CAPSENSE_MW_VERSION            (200)
    #elif (CY_CAPSENSE_MW_VERSION_MAJOR == 1)
        #define CY_CAPSENSE_MW_VERSION            (100)
    #else
        #define CY_CAPSENSE_MW_VERSION            (100)
    #endif
#endif

/* Check the used Middleware version */
#if (CY_CAPSENSE_MW_VERSION_REQUIRED > CY_CAPSENSE_MW_VERSION)
    #error The CapSense Configurator requires a newer version of the CapSense Middleware. Update the CapSense Middleware in your project.
#endif

#define CY_CAPSENSE_BIST_SUPPORTED                ((CY_CAPSENSE_MW_VERSION >= 210) && (CY_CAPSENSE_MW_VERSION != 300))

#if defined(__cplusplus)
extern "C" {
#endif

/*Widget names */
#define CY_CAPSENSE_BUTTON0_WDGT_ID                                              (0u)
#define CY_CAPSENSE_BUTTON1_WDGT_ID                                              (1u)

/* Button0 sensor names */
#define CY_CAPSENSE_BUTTON0_SNS0_ID                                              (0u)

/* Button0 node names */
#define CY_CAPSENSE_BUTTON0_RX0_TX0_ID                                           (0u)

/* Button0 sensor element IDs */
#define CY_CAPSENSE_BUTTON0_RX0_ID                                               (0u)
#define CY_CAPSENSE_BUTTON0_TX0_ID                                               (1u)

/* Button1 sensor names */
#define CY_CAPSENSE_BUTTON1_SNS0_ID                                              (0u)

/* Button1 node names */
#define CY_CAPSENSE_BUTTON1_RX0_TX0_ID                                           (0u)

/* Button1 sensor element IDs */
#define CY_CAPSENSE_BUTTON1_RX0_ID                                               (0u)
#define CY_CAPSENSE_BUTTON1_TX0_ID                                               (1u)

/* Sensing Methods */
#define CY_CAPSENSE_CSD_EN                                                       (0u)
#define CY_CAPSENSE_CSX_EN                                                       (1u)
#define CY_CAPSENSE_CSD_CALIBRATION_EN                                           (0u)
#define CY_CAPSENSE_CSX_CALIBRATION_EN                                           (1u)
#define CY_CAPSENSE_SMARTSENSE_FULL_EN                                           (0u)
#define CY_CAPSENSE_SMARTSENSE_HW_EN                                             (0u)
#define CY_CAPSENSE_SMARTSENSE_DISABLED                                          (1u)
#define CY_CAPSENSE_CSD_SHIELD_EN                                                (0u)

/* Filtering */
#define CY_CAPSENSE_ADAPTIVE_FILTER_EN                                           (0u)
#define CY_CAPSENSE_BALLISTIC_MULTIPLIER_EN                                      (0u)
#define CY_CAPSENSE_RAWCOUNT_FILTER_EN                                           (0u)
#define CY_CAPSENSE_POSITION_FILTER_EN                                           (0u)
#define CY_CAPSENSE_CSD_POSITION_FILTER_EN                                       (0u)
#define CY_CAPSENSE_CSX_POSITION_FILTER_EN                                       (0u)

/* Widgets */
#define CY_CAPSENSE_CSD_BUTTON_EN                                                (0u)
#define CY_CAPSENSE_CSD_MATRIX_EN                                                (0u)
#define CY_CAPSENSE_CSD_SLIDER_EN                                                (0u)
#define CY_CAPSENSE_CSD_TOUCHPAD_EN                                              (0u)
#define CY_CAPSENSE_CSD_PROXIMITY_EN                                             (0u)
#define CY_CAPSENSE_CSX_BUTTON_EN                                                (1u)
#define CY_CAPSENSE_CSX_MATRIX_EN                                                (0u)
#define CY_CAPSENSE_CSX_TOUCHPAD_EN                                              (0u)
#define CY_CAPSENSE_ADVANCED_CENTROID_5X5_EN                                     (0u)
#define CY_CAPSENSE_CSD_LINEAR_SLIDER_EN                                         (0u)
#define CY_CAPSENSE_CSD_RADIAL_SLIDER_EN                                         (0u)
#define CY_CAPSENSE_CSD_DIPLEX_SLIDER_EN                                         (0u)

/* Features */
#define CY_CAPSENSE_GESTURE_EN                                                   (0u)
#define CY_CAPSENSE_MULTI_FREQUENCY_SCAN_EN                                      (0u)
#define CY_CAPSENSE_SNS_AUTO_RESET_EN                                            (0u)
#define CY_CAPSENSE_BIST_EN                                                      (0u)


typedef struct {
    cy_stc_capsense_common_context_t commonContext;
    cy_stc_capsense_widget_context_t widgetContext[2];
    cy_stc_capsense_sensor_context_t sensorContext[2];
} cy_stc_capsense_tuner_t;

extern cy_stc_capsense_tuner_t cy_capsense_tuner;

extern cy_stc_capsense_context_t cy_capsense_context;

/* RAM Data structure register definitions */
#define CY_CAPSENSE_CONFIG_ID_VALUE                                              (cy_capsense_tuner.commonContext.configId)
#define CY_CAPSENSE_CONFIG_ID_OFFSET                                             (0u)
#define CY_CAPSENSE_CONFIG_ID_SIZE                                               (2u)
#define CY_CAPSENSE_CONFIG_ID_PARAM_ID                                           (0x02000000u)

#define CY_CAPSENSE_TUNER_CMD_VALUE                                              (cy_capsense_tuner.commonContext.tunerCmd)
#define CY_CAPSENSE_TUNER_CMD_OFFSET                                             (2u)
#define CY_CAPSENSE_TUNER_CMD_SIZE                                               (2u)
#define CY_CAPSENSE_TUNER_CMD_PARAM_ID                                           (0x02000002u)

#define CY_CAPSENSE_SCAN_COUNTER_VALUE                                           (cy_capsense_tuner.commonContext.scanCounter)
#define CY_CAPSENSE_SCAN_COUNTER_OFFSET                                          (4u)
#define CY_CAPSENSE_SCAN_COUNTER_SIZE                                            (2u)
#define CY_CAPSENSE_SCAN_COUNTER_PARAM_ID                                        (0x02000004u)

#define CY_CAPSENSE_TUNER_ST_VALUE                                               (cy_capsense_tuner.commonContext.tunerSt)
#define CY_CAPSENSE_TUNER_ST_OFFSET                                              (6u)
#define CY_CAPSENSE_TUNER_ST_SIZE                                                (1u)
#define CY_CAPSENSE_TUNER_ST_PARAM_ID                                            (0x01000006u)

#define CY_CAPSENSE_INITDONE_VALUE                                               (cy_capsense_tuner.commonContext.initDone)
#define CY_CAPSENSE_INITDONE_OFFSET                                              (7u)
#define CY_CAPSENSE_INITDONE_SIZE                                                (1u)
#define CY_CAPSENSE_INITDONE_PARAM_ID                                            (0x01000007u)

#define CY_CAPSENSE_PTRSSCALLBACK_VALUE                                          (cy_capsense_tuner.commonContext.ptrSSCallback)
#define CY_CAPSENSE_PTRSSCALLBACK_OFFSET                                         (8u)
#define CY_CAPSENSE_PTRSSCALLBACK_SIZE                                           (4u)
#define CY_CAPSENSE_PTRSSCALLBACK_PARAM_ID                                       (0x03000008u)

#define CY_CAPSENSE_PTREOSCALLBACK_VALUE                                         (cy_capsense_tuner.commonContext.ptrEOSCallback)
#define CY_CAPSENSE_PTREOSCALLBACK_OFFSET                                        (12u)
#define CY_CAPSENSE_PTREOSCALLBACK_SIZE                                          (4u)
#define CY_CAPSENSE_PTREOSCALLBACK_PARAM_ID                                      (0x0300000cu)

#define CY_CAPSENSE_PTRTUNERSENDCALLBACK_VALUE                                   (cy_capsense_tuner.commonContext.ptrTunerSendCallback)
#define CY_CAPSENSE_PTRTUNERSENDCALLBACK_OFFSET                                  (16u)
#define CY_CAPSENSE_PTRTUNERSENDCALLBACK_SIZE                                    (4u)
#define CY_CAPSENSE_PTRTUNERSENDCALLBACK_PARAM_ID                                (0x03000010u)

#define CY_CAPSENSE_PTRTUNERRECEIVECALLBACK_VALUE                                (cy_capsense_tuner.commonContext.ptrTunerReceiveCallback)
#define CY_CAPSENSE_PTRTUNERRECEIVECALLBACK_OFFSET                               (20u)
#define CY_CAPSENSE_PTRTUNERRECEIVECALLBACK_SIZE                                 (4u)
#define CY_CAPSENSE_PTRTUNERRECEIVECALLBACK_PARAM_ID                             (0x03000014u)

#define CY_CAPSENSE_STATUS_VALUE                                                 (cy_capsense_tuner.commonContext.status)
#define CY_CAPSENSE_STATUS_OFFSET                                                (24u)
#define CY_CAPSENSE_STATUS_SIZE                                                  (4u)
#define CY_CAPSENSE_STATUS_PARAM_ID                                              (0x03000018u)

#define CY_CAPSENSE_TIMESTAMPINTERVAL_VALUE                                      (cy_capsense_tuner.commonContext.timestampInterval)
#define CY_CAPSENSE_TIMESTAMPINTERVAL_OFFSET                                     (28u)
#define CY_CAPSENSE_TIMESTAMPINTERVAL_SIZE                                       (4u)
#define CY_CAPSENSE_TIMESTAMPINTERVAL_PARAM_ID                                   (0x0300001cu)

#define CY_CAPSENSE_TIMESTAMP_VALUE                                              (cy_capsense_tuner.commonContext.timestamp)
#define CY_CAPSENSE_TIMESTAMP_OFFSET                                             (32u)
#define CY_CAPSENSE_TIMESTAMP_SIZE                                               (4u)
#define CY_CAPSENSE_TIMESTAMP_PARAM_ID                                           (0x03000020u)

#define CY_CAPSENSE_TUNER_CNT_VALUE                                              (cy_capsense_tuner.commonContext.tunerCnt)
#define CY_CAPSENSE_TUNER_CNT_OFFSET                                             (36u)
#define CY_CAPSENSE_TUNER_CNT_SIZE                                               (1u)
#define CY_CAPSENSE_TUNER_CNT_PARAM_ID                                           (0x01000024u)

#define CY_CAPSENSE_NUM_PRO_DUMMY_SUB_CONVS_VALUE                                (cy_capsense_tuner.commonContext.numFineInitCycles)
#define CY_CAPSENSE_NUM_PRO_DUMMY_SUB_CONVS_OFFSET                               (37u)
#define CY_CAPSENSE_NUM_PRO_DUMMY_SUB_CONVS_SIZE                                 (1u)
#define CY_CAPSENSE_NUM_PRO_DUMMY_SUB_CONVS_PARAM_ID                             (0x01000025u)

#define CY_CAPSENSE_NUM_PRO_WAIT_CYCLES_VALUE                                    (cy_capsense_tuner.commonContext.numFineInitWaitCycles)
#define CY_CAPSENSE_NUM_PRO_WAIT_CYCLES_OFFSET                                   (38u)
#define CY_CAPSENSE_NUM_PRO_WAIT_CYCLES_SIZE                                     (2u)
#define CY_CAPSENSE_NUM_PRO_WAIT_CYCLES_PARAM_ID                                 (0x02000026u)

#define CY_CAPSENSE_LFSR_POLY_VALUE                                              (cy_capsense_tuner.commonContext.lfsrPoly)
#define CY_CAPSENSE_LFSR_POLY_OFFSET                                             (40u)
#define CY_CAPSENSE_LFSR_POLY_SIZE                                               (2u)
#define CY_CAPSENSE_LFSR_POLY_PARAM_ID                                           (0x02000028u)

#define CY_CAPSENSE_LFSR_SCALE_VALUE                                             (cy_capsense_tuner.commonContext.lfsrScale)
#define CY_CAPSENSE_LFSR_SCALE_OFFSET                                            (42u)
#define CY_CAPSENSE_LFSR_SCALE_SIZE                                              (1u)
#define CY_CAPSENSE_LFSR_SCALE_PARAM_ID                                          (0x0100002au)

#define CY_CAPSENSE_SEL_FL_VALUE                                                 (cy_capsense_tuner.commonContext.cdacDitherSeed)
#define CY_CAPSENSE_SEL_FL_OFFSET                                                (43u)
#define CY_CAPSENSE_SEL_FL_SIZE                                                  (1u)
#define CY_CAPSENSE_SEL_FL_PARAM_ID                                              (0x0100002bu)

#define CY_CAPSENSE_LFSR_POLY_FL_VALUE                                           (cy_capsense_tuner.commonContext.cdacDitherPoly)
#define CY_CAPSENSE_LFSR_POLY_FL_OFFSET                                          (44u)
#define CY_CAPSENSE_LFSR_POLY_FL_SIZE                                            (1u)
#define CY_CAPSENSE_LFSR_POLY_FL_PARAM_ID                                        (0x0100002cu)

#define CY_CAPSENSE_MOD_CLK_DIVIDER_VALUE                                        (cy_capsense_tuner.commonContext.modClk)
#define CY_CAPSENSE_MOD_CLK_DIVIDER_OFFSET                                       (45u)
#define CY_CAPSENSE_MOD_CLK_DIVIDER_SIZE                                         (1u)
#define CY_CAPSENSE_MOD_CLK_DIVIDER_PARAM_ID                                     (0x0100002du)

#define CY_CAPSENSE_BUTTON0_FINGER_CP_VALUE                                      (cy_capsense_tuner.widgetContext[0].fingerCap)
#define CY_CAPSENSE_BUTTON0_FINGER_CP_OFFSET                                     (48u)
#define CY_CAPSENSE_BUTTON0_FINGER_CP_SIZE                                       (2u)
#define CY_CAPSENSE_BUTTON0_FINGER_CP_PARAM_ID                                   (0x06000030u)

#define CY_CAPSENSE_BUTTON0_SIGPFC_VALUE                                         (cy_capsense_tuner.widgetContext[0].sigPFC)
#define CY_CAPSENSE_BUTTON0_SIGPFC_OFFSET                                        (50u)
#define CY_CAPSENSE_BUTTON0_SIGPFC_SIZE                                          (2u)
#define CY_CAPSENSE_BUTTON0_SIGPFC_PARAM_ID                                      (0x06000032u)

#define CY_CAPSENSE_BUTTON0_MAXRAWCOUNT_VALUE                                    (cy_capsense_tuner.widgetContext[0].maxRawCount)
#define CY_CAPSENSE_BUTTON0_MAXRAWCOUNT_OFFSET                                   (52u)
#define CY_CAPSENSE_BUTTON0_MAXRAWCOUNT_SIZE                                     (2u)
#define CY_CAPSENSE_BUTTON0_MAXRAWCOUNT_PARAM_ID                                 (0x02000034u)

#define CY_CAPSENSE_BUTTON0_FINGER_TH_VALUE                                      (cy_capsense_tuner.widgetContext[0].fingerTh)
#define CY_CAPSENSE_BUTTON0_FINGER_TH_OFFSET                                     (54u)
#define CY_CAPSENSE_BUTTON0_FINGER_TH_SIZE                                       (2u)
#define CY_CAPSENSE_BUTTON0_FINGER_TH_PARAM_ID                                   (0x06000036u)

#define CY_CAPSENSE_BUTTON0_PROX_TOUCH_TH_VALUE                                  (cy_capsense_tuner.widgetContext[0].proxTh)
#define CY_CAPSENSE_BUTTON0_PROX_TOUCH_TH_OFFSET                                 (56u)
#define CY_CAPSENSE_BUTTON0_PROX_TOUCH_TH_SIZE                                   (2u)
#define CY_CAPSENSE_BUTTON0_PROX_TOUCH_TH_PARAM_ID                               (0x06000038u)

#define CY_CAPSENSE_BUTTON0_LOW_BSLN_RST_VALUE                                   (cy_capsense_tuner.widgetContext[0].lowBslnRst)
#define CY_CAPSENSE_BUTTON0_LOW_BSLN_RST_OFFSET                                  (58u)
#define CY_CAPSENSE_BUTTON0_LOW_BSLN_RST_SIZE                                    (2u)
#define CY_CAPSENSE_BUTTON0_LOW_BSLN_RST_PARAM_ID                                (0x0600003au)

#define CY_CAPSENSE_BUTTON0_TX_CLK_VALUE                                         (cy_capsense_tuner.widgetContext[0].snsClk)
#define CY_CAPSENSE_BUTTON0_TX_CLK_OFFSET                                        (60u)
#define CY_CAPSENSE_BUTTON0_TX_CLK_SIZE                                          (2u)
#define CY_CAPSENSE_BUTTON0_TX_CLK_PARAM_ID                                      (0x0600003cu)

#define CY_CAPSENSE_BUTTON0_ROW_SNS_CLK_VALUE                                    (cy_capsense_tuner.widgetContext[0].rowSnsClk)
#define CY_CAPSENSE_BUTTON0_ROW_SNS_CLK_OFFSET                                   (62u)
#define CY_CAPSENSE_BUTTON0_ROW_SNS_CLK_SIZE                                     (2u)
#define CY_CAPSENSE_BUTTON0_ROW_SNS_CLK_PARAM_ID                                 (0x0600003eu)

#define CY_CAPSENSE_BUTTON0_GESTURE_DETECTED_VALUE                               (cy_capsense_tuner.widgetContext[0].gestureDetected)
#define CY_CAPSENSE_BUTTON0_GESTURE_DETECTED_OFFSET                              (64u)
#define CY_CAPSENSE_BUTTON0_GESTURE_DETECTED_SIZE                                (2u)
#define CY_CAPSENSE_BUTTON0_GESTURE_DETECTED_PARAM_ID                            (0x02000040u)

#define CY_CAPSENSE_BUTTON0_GESTURE_DIRECTION_VALUE                              (cy_capsense_tuner.widgetContext[0].gestureDirection)
#define CY_CAPSENSE_BUTTON0_GESTURE_DIRECTION_OFFSET                             (66u)
#define CY_CAPSENSE_BUTTON0_GESTURE_DIRECTION_SIZE                               (2u)
#define CY_CAPSENSE_BUTTON0_GESTURE_DIRECTION_PARAM_ID                           (0x02000042u)

#define CY_CAPSENSE_BUTTON0_XDELTA_VALUE                                         (cy_capsense_tuner.widgetContext[0].xDelta)
#define CY_CAPSENSE_BUTTON0_XDELTA_OFFSET                                        (68u)
#define CY_CAPSENSE_BUTTON0_XDELTA_SIZE                                          (2u)
#define CY_CAPSENSE_BUTTON0_XDELTA_PARAM_ID                                      (0x02000044u)

#define CY_CAPSENSE_BUTTON0_YDELTA_VALUE                                         (cy_capsense_tuner.widgetContext[0].yDelta)
#define CY_CAPSENSE_BUTTON0_YDELTA_OFFSET                                        (70u)
#define CY_CAPSENSE_BUTTON0_YDELTA_SIZE                                          (2u)
#define CY_CAPSENSE_BUTTON0_YDELTA_PARAM_ID                                      (0x02000046u)

#define CY_CAPSENSE_BUTTON0_NOISE_TH_VALUE                                       (cy_capsense_tuner.widgetContext[0].noiseTh)
#define CY_CAPSENSE_BUTTON0_NOISE_TH_OFFSET                                      (72u)
#define CY_CAPSENSE_BUTTON0_NOISE_TH_SIZE                                        (1u)
#define CY_CAPSENSE_BUTTON0_NOISE_TH_PARAM_ID                                    (0x05000048u)

#define CY_CAPSENSE_BUTTON0_NNOISE_TH_VALUE                                      (cy_capsense_tuner.widgetContext[0].nNoiseTh)
#define CY_CAPSENSE_BUTTON0_NNOISE_TH_OFFSET                                     (73u)
#define CY_CAPSENSE_BUTTON0_NNOISE_TH_SIZE                                       (1u)
#define CY_CAPSENSE_BUTTON0_NNOISE_TH_PARAM_ID                                   (0x05000049u)

#define CY_CAPSENSE_BUTTON0_HYSTERESIS_VALUE                                     (cy_capsense_tuner.widgetContext[0].hysteresis)
#define CY_CAPSENSE_BUTTON0_HYSTERESIS_OFFSET                                    (74u)
#define CY_CAPSENSE_BUTTON0_HYSTERESIS_SIZE                                      (1u)
#define CY_CAPSENSE_BUTTON0_HYSTERESIS_PARAM_ID                                  (0x0500004au)

#define CY_CAPSENSE_BUTTON0_ON_DEBOUNCE_VALUE                                    (cy_capsense_tuner.widgetContext[0].onDebounce)
#define CY_CAPSENSE_BUTTON0_ON_DEBOUNCE_OFFSET                                   (75u)
#define CY_CAPSENSE_BUTTON0_ON_DEBOUNCE_SIZE                                     (1u)
#define CY_CAPSENSE_BUTTON0_ON_DEBOUNCE_PARAM_ID                                 (0x0500004bu)

#define CY_CAPSENSE_BUTTON0_CLK_SOURCE_VALUE                                     (cy_capsense_tuner.widgetContext[0].snsClkSource)
#define CY_CAPSENSE_BUTTON0_CLK_SOURCE_OFFSET                                    (76u)
#define CY_CAPSENSE_BUTTON0_CLK_SOURCE_SIZE                                      (1u)
#define CY_CAPSENSE_BUTTON0_CLK_SOURCE_PARAM_ID                                  (0x0500004cu)

#define CY_CAPSENSE_BUTTON0_REGULAR_IIR_BL_N_VALUE                               (cy_capsense_tuner.widgetContext[0].bslnCoeff)
#define CY_CAPSENSE_BUTTON0_REGULAR_IIR_BL_N_OFFSET                              (77u)
#define CY_CAPSENSE_BUTTON0_REGULAR_IIR_BL_N_SIZE                                (1u)
#define CY_CAPSENSE_BUTTON0_REGULAR_IIR_BL_N_PARAM_ID                            (0x0100004du)

#define CY_CAPSENSE_BUTTON0_STATUS_VALUE                                         (cy_capsense_tuner.widgetContext[0].status)
#define CY_CAPSENSE_BUTTON0_STATUS_OFFSET                                        (78u)
#define CY_CAPSENSE_BUTTON0_STATUS_SIZE                                          (1u)
#define CY_CAPSENSE_BUTTON0_STATUS_PARAM_ID                                      (0x0100004eu)

#define CY_CAPSENSE_BUTTON0_PTRPOSITION_VALUE                                    (cy_capsense_tuner.widgetContext[0].wdTouch.ptrPosition)
#define CY_CAPSENSE_BUTTON0_PTRPOSITION_OFFSET                                   (80u)
#define CY_CAPSENSE_BUTTON0_PTRPOSITION_SIZE                                     (4u)
#define CY_CAPSENSE_BUTTON0_PTRPOSITION_PARAM_ID                                 (0x03000050u)

#define CY_CAPSENSE_BUTTON0_NUM_POSITIONS_VALUE                                  (cy_capsense_tuner.widgetContext[0].wdTouch.numPosition)
#define CY_CAPSENSE_BUTTON0_NUM_POSITIONS_OFFSET                                 (84u)
#define CY_CAPSENSE_BUTTON0_NUM_POSITIONS_SIZE                                   (1u)
#define CY_CAPSENSE_BUTTON0_NUM_POSITIONS_PARAM_ID                               (0x01000054u)

#define CY_CAPSENSE_BUTTON0_NUM_SUBCONVERSIONS_VALUE                             (cy_capsense_tuner.widgetContext[0].numSubConversions)
#define CY_CAPSENSE_BUTTON0_NUM_SUBCONVERSIONS_OFFSET                            (88u)
#define CY_CAPSENSE_BUTTON0_NUM_SUBCONVERSIONS_SIZE                              (2u)
#define CY_CAPSENSE_BUTTON0_NUM_SUBCONVERSIONS_PARAM_ID                          (0x02000058u)

#define CY_CAPSENSE_BUTTON0_CDAC_REF0_VALUE                                      (cy_capsense_tuner.widgetContext[0].cdacRef[0])
#define CY_CAPSENSE_BUTTON0_CDAC_REF0_OFFSET                                     (90u)
#define CY_CAPSENSE_BUTTON0_CDAC_REF0_SIZE                                       (1u)
#define CY_CAPSENSE_BUTTON0_CDAC_REF0_PARAM_ID                                   (0x0100005au)

#define CY_CAPSENSE_BUTTON0_CDAC_REF1_VALUE                                      (cy_capsense_tuner.widgetContext[0].cdacRef[1])
#define CY_CAPSENSE_BUTTON0_CDAC_REF1_OFFSET                                     (91u)
#define CY_CAPSENSE_BUTTON0_CDAC_REF1_SIZE                                       (1u)
#define CY_CAPSENSE_BUTTON0_CDAC_REF1_PARAM_ID                                   (0x0100005bu)

#define CY_CAPSENSE_BUTTON0_CDAC_REF2_VALUE                                      (cy_capsense_tuner.widgetContext[0].cdacRef[2])
#define CY_CAPSENSE_BUTTON0_CDAC_REF2_OFFSET                                     (92u)
#define CY_CAPSENSE_BUTTON0_CDAC_REF2_SIZE                                       (1u)
#define CY_CAPSENSE_BUTTON0_CDAC_REF2_PARAM_ID                                   (0x0100005cu)

#define CY_CAPSENSE_BUTTON0_ROW_CDAC_REF0_VALUE                                  (cy_capsense_tuner.widgetContext[0].rowCdacRef[0])
#define CY_CAPSENSE_BUTTON0_ROW_CDAC_REF0_OFFSET                                 (93u)
#define CY_CAPSENSE_BUTTON0_ROW_CDAC_REF0_SIZE                                   (1u)
#define CY_CAPSENSE_BUTTON0_ROW_CDAC_REF0_PARAM_ID                               (0x0100005du)

#define CY_CAPSENSE_BUTTON0_ROW_CDAC_REF1_VALUE                                  (cy_capsense_tuner.widgetContext[0].rowCdacRef[1])
#define CY_CAPSENSE_BUTTON0_ROW_CDAC_REF1_OFFSET                                 (94u)
#define CY_CAPSENSE_BUTTON0_ROW_CDAC_REF1_SIZE                                   (1u)
#define CY_CAPSENSE_BUTTON0_ROW_CDAC_REF1_PARAM_ID                               (0x0100005eu)

#define CY_CAPSENSE_BUTTON0_ROW_CDAC_REF2_VALUE                                  (cy_capsense_tuner.widgetContext[0].rowCdacRef[2])
#define CY_CAPSENSE_BUTTON0_ROW_CDAC_REF2_OFFSET                                 (95u)
#define CY_CAPSENSE_BUTTON0_ROW_CDAC_REF2_SIZE                                   (1u)
#define CY_CAPSENSE_BUTTON0_ROW_CDAC_REF2_PARAM_ID                               (0x0100005fu)

#define CY_CAPSENSE_BUTTON0_CIC_RATE_VALUE                                       (cy_capsense_tuner.widgetContext[0].cicRate)
#define CY_CAPSENSE_BUTTON0_CIC_RATE_OFFSET                                      (96u)
#define CY_CAPSENSE_BUTTON0_CIC_RATE_SIZE                                        (1u)
#define CY_CAPSENSE_BUTTON0_CIC_RATE_PARAM_ID                                    (0x01000060u)

#define CY_CAPSENSE_BUTTON0_CDAC_DITHER_EN_VALUE                                 (cy_capsense_tuner.widgetContext[0].cdacDitherEn)
#define CY_CAPSENSE_BUTTON0_CDAC_DITHER_EN_OFFSET                                (97u)
#define CY_CAPSENSE_BUTTON0_CDAC_DITHER_EN_SIZE                                  (1u)
#define CY_CAPSENSE_BUTTON0_CDAC_DITHER_EN_PARAM_ID                              (0x01000061u)

#define CY_CAPSENSE_BUTTON0_CDAC_DITHER_VALUE_VALUE                              (cy_capsense_tuner.widgetContext[0].cdacDitherValue)
#define CY_CAPSENSE_BUTTON0_CDAC_DITHER_VALUE_OFFSET                             (98u)
#define CY_CAPSENSE_BUTTON0_CDAC_DITHER_VALUE_SIZE                               (1u)
#define CY_CAPSENSE_BUTTON0_CDAC_DITHER_VALUE_PARAM_ID                           (0x01000062u)

#define CY_CAPSENSE_BUTTON0_COARSE_INIT_BYPASS_EN_VALUE                          (cy_capsense_tuner.widgetContext[0].coarseInitBypassEn)
#define CY_CAPSENSE_BUTTON0_COARSE_INIT_BYPASS_EN_OFFSET                         (99u)
#define CY_CAPSENSE_BUTTON0_COARSE_INIT_BYPASS_EN_SIZE                           (1u)
#define CY_CAPSENSE_BUTTON0_COARSE_INIT_BYPASS_EN_PARAM_ID                       (0x01000063u)

#define CY_CAPSENSE_BUTTON0_COMP_DIV_VALUE                                       (cy_capsense_tuner.widgetContext[0].cdacCompDivider)
#define CY_CAPSENSE_BUTTON0_COMP_DIV_OFFSET                                      (100u)
#define CY_CAPSENSE_BUTTON0_COMP_DIV_SIZE                                        (2u)
#define CY_CAPSENSE_BUTTON0_COMP_DIV_PARAM_ID                                    (0x02000064u)

#define CY_CAPSENSE_BUTTON1_FINGER_CP_VALUE                                      (cy_capsense_tuner.widgetContext[1].fingerCap)
#define CY_CAPSENSE_BUTTON1_FINGER_CP_OFFSET                                     (104u)
#define CY_CAPSENSE_BUTTON1_FINGER_CP_SIZE                                       (2u)
#define CY_CAPSENSE_BUTTON1_FINGER_CP_PARAM_ID                                   (0x06010068u)

#define CY_CAPSENSE_BUTTON1_SIGPFC_VALUE                                         (cy_capsense_tuner.widgetContext[1].sigPFC)
#define CY_CAPSENSE_BUTTON1_SIGPFC_OFFSET                                        (106u)
#define CY_CAPSENSE_BUTTON1_SIGPFC_SIZE                                          (2u)
#define CY_CAPSENSE_BUTTON1_SIGPFC_PARAM_ID                                      (0x0601006au)

#define CY_CAPSENSE_BUTTON1_MAXRAWCOUNT_VALUE                                    (cy_capsense_tuner.widgetContext[1].maxRawCount)
#define CY_CAPSENSE_BUTTON1_MAXRAWCOUNT_OFFSET                                   (108u)
#define CY_CAPSENSE_BUTTON1_MAXRAWCOUNT_SIZE                                     (2u)
#define CY_CAPSENSE_BUTTON1_MAXRAWCOUNT_PARAM_ID                                 (0x0201006cu)

#define CY_CAPSENSE_BUTTON1_FINGER_TH_VALUE                                      (cy_capsense_tuner.widgetContext[1].fingerTh)
#define CY_CAPSENSE_BUTTON1_FINGER_TH_OFFSET                                     (110u)
#define CY_CAPSENSE_BUTTON1_FINGER_TH_SIZE                                       (2u)
#define CY_CAPSENSE_BUTTON1_FINGER_TH_PARAM_ID                                   (0x0601006eu)

#define CY_CAPSENSE_BUTTON1_PROX_TOUCH_TH_VALUE                                  (cy_capsense_tuner.widgetContext[1].proxTh)
#define CY_CAPSENSE_BUTTON1_PROX_TOUCH_TH_OFFSET                                 (112u)
#define CY_CAPSENSE_BUTTON1_PROX_TOUCH_TH_SIZE                                   (2u)
#define CY_CAPSENSE_BUTTON1_PROX_TOUCH_TH_PARAM_ID                               (0x06010070u)

#define CY_CAPSENSE_BUTTON1_LOW_BSLN_RST_VALUE                                   (cy_capsense_tuner.widgetContext[1].lowBslnRst)
#define CY_CAPSENSE_BUTTON1_LOW_BSLN_RST_OFFSET                                  (114u)
#define CY_CAPSENSE_BUTTON1_LOW_BSLN_RST_SIZE                                    (2u)
#define CY_CAPSENSE_BUTTON1_LOW_BSLN_RST_PARAM_ID                                (0x06010072u)

#define CY_CAPSENSE_BUTTON1_TX_CLK_VALUE                                         (cy_capsense_tuner.widgetContext[1].snsClk)
#define CY_CAPSENSE_BUTTON1_TX_CLK_OFFSET                                        (116u)
#define CY_CAPSENSE_BUTTON1_TX_CLK_SIZE                                          (2u)
#define CY_CAPSENSE_BUTTON1_TX_CLK_PARAM_ID                                      (0x06010074u)

#define CY_CAPSENSE_BUTTON1_ROW_SNS_CLK_VALUE                                    (cy_capsense_tuner.widgetContext[1].rowSnsClk)
#define CY_CAPSENSE_BUTTON1_ROW_SNS_CLK_OFFSET                                   (118u)
#define CY_CAPSENSE_BUTTON1_ROW_SNS_CLK_SIZE                                     (2u)
#define CY_CAPSENSE_BUTTON1_ROW_SNS_CLK_PARAM_ID                                 (0x06010076u)

#define CY_CAPSENSE_BUTTON1_GESTURE_DETECTED_VALUE                               (cy_capsense_tuner.widgetContext[1].gestureDetected)
#define CY_CAPSENSE_BUTTON1_GESTURE_DETECTED_OFFSET                              (120u)
#define CY_CAPSENSE_BUTTON1_GESTURE_DETECTED_SIZE                                (2u)
#define CY_CAPSENSE_BUTTON1_GESTURE_DETECTED_PARAM_ID                            (0x02010078u)

#define CY_CAPSENSE_BUTTON1_GESTURE_DIRECTION_VALUE                              (cy_capsense_tuner.widgetContext[1].gestureDirection)
#define CY_CAPSENSE_BUTTON1_GESTURE_DIRECTION_OFFSET                             (122u)
#define CY_CAPSENSE_BUTTON1_GESTURE_DIRECTION_SIZE                               (2u)
#define CY_CAPSENSE_BUTTON1_GESTURE_DIRECTION_PARAM_ID                           (0x0201007au)

#define CY_CAPSENSE_BUTTON1_XDELTA_VALUE                                         (cy_capsense_tuner.widgetContext[1].xDelta)
#define CY_CAPSENSE_BUTTON1_XDELTA_OFFSET                                        (124u)
#define CY_CAPSENSE_BUTTON1_XDELTA_SIZE                                          (2u)
#define CY_CAPSENSE_BUTTON1_XDELTA_PARAM_ID                                      (0x0201007cu)

#define CY_CAPSENSE_BUTTON1_YDELTA_VALUE                                         (cy_capsense_tuner.widgetContext[1].yDelta)
#define CY_CAPSENSE_BUTTON1_YDELTA_OFFSET                                        (126u)
#define CY_CAPSENSE_BUTTON1_YDELTA_SIZE                                          (2u)
#define CY_CAPSENSE_BUTTON1_YDELTA_PARAM_ID                                      (0x0201007eu)

#define CY_CAPSENSE_BUTTON1_NOISE_TH_VALUE                                       (cy_capsense_tuner.widgetContext[1].noiseTh)
#define CY_CAPSENSE_BUTTON1_NOISE_TH_OFFSET                                      (128u)
#define CY_CAPSENSE_BUTTON1_NOISE_TH_SIZE                                        (1u)
#define CY_CAPSENSE_BUTTON1_NOISE_TH_PARAM_ID                                    (0x05010080u)

#define CY_CAPSENSE_BUTTON1_NNOISE_TH_VALUE                                      (cy_capsense_tuner.widgetContext[1].nNoiseTh)
#define CY_CAPSENSE_BUTTON1_NNOISE_TH_OFFSET                                     (129u)
#define CY_CAPSENSE_BUTTON1_NNOISE_TH_SIZE                                       (1u)
#define CY_CAPSENSE_BUTTON1_NNOISE_TH_PARAM_ID                                   (0x05010081u)

#define CY_CAPSENSE_BUTTON1_HYSTERESIS_VALUE                                     (cy_capsense_tuner.widgetContext[1].hysteresis)
#define CY_CAPSENSE_BUTTON1_HYSTERESIS_OFFSET                                    (130u)
#define CY_CAPSENSE_BUTTON1_HYSTERESIS_SIZE                                      (1u)
#define CY_CAPSENSE_BUTTON1_HYSTERESIS_PARAM_ID                                  (0x05010082u)

#define CY_CAPSENSE_BUTTON1_ON_DEBOUNCE_VALUE                                    (cy_capsense_tuner.widgetContext[1].onDebounce)
#define CY_CAPSENSE_BUTTON1_ON_DEBOUNCE_OFFSET                                   (131u)
#define CY_CAPSENSE_BUTTON1_ON_DEBOUNCE_SIZE                                     (1u)
#define CY_CAPSENSE_BUTTON1_ON_DEBOUNCE_PARAM_ID                                 (0x05010083u)

#define CY_CAPSENSE_BUTTON1_CLK_SOURCE_VALUE                                     (cy_capsense_tuner.widgetContext[1].snsClkSource)
#define CY_CAPSENSE_BUTTON1_CLK_SOURCE_OFFSET                                    (132u)
#define CY_CAPSENSE_BUTTON1_CLK_SOURCE_SIZE                                      (1u)
#define CY_CAPSENSE_BUTTON1_CLK_SOURCE_PARAM_ID                                  (0x05010084u)

#define CY_CAPSENSE_BUTTON1_REGULAR_IIR_BL_N_VALUE                               (cy_capsense_tuner.widgetContext[1].bslnCoeff)
#define CY_CAPSENSE_BUTTON1_REGULAR_IIR_BL_N_OFFSET                              (133u)
#define CY_CAPSENSE_BUTTON1_REGULAR_IIR_BL_N_SIZE                                (1u)
#define CY_CAPSENSE_BUTTON1_REGULAR_IIR_BL_N_PARAM_ID                            (0x01010085u)

#define CY_CAPSENSE_BUTTON1_STATUS_VALUE                                         (cy_capsense_tuner.widgetContext[1].status)
#define CY_CAPSENSE_BUTTON1_STATUS_OFFSET                                        (134u)
#define CY_CAPSENSE_BUTTON1_STATUS_SIZE                                          (1u)
#define CY_CAPSENSE_BUTTON1_STATUS_PARAM_ID                                      (0x01010086u)

#define CY_CAPSENSE_BUTTON1_PTRPOSITION_VALUE                                    (cy_capsense_tuner.widgetContext[1].wdTouch.ptrPosition)
#define CY_CAPSENSE_BUTTON1_PTRPOSITION_OFFSET                                   (136u)
#define CY_CAPSENSE_BUTTON1_PTRPOSITION_SIZE                                     (4u)
#define CY_CAPSENSE_BUTTON1_PTRPOSITION_PARAM_ID                                 (0x03010088u)

#define CY_CAPSENSE_BUTTON1_NUM_POSITIONS_VALUE                                  (cy_capsense_tuner.widgetContext[1].wdTouch.numPosition)
#define CY_CAPSENSE_BUTTON1_NUM_POSITIONS_OFFSET                                 (140u)
#define CY_CAPSENSE_BUTTON1_NUM_POSITIONS_SIZE                                   (1u)
#define CY_CAPSENSE_BUTTON1_NUM_POSITIONS_PARAM_ID                               (0x0101008cu)

#define CY_CAPSENSE_BUTTON1_NUM_SUBCONVERSIONS_VALUE                             (cy_capsense_tuner.widgetContext[1].numSubConversions)
#define CY_CAPSENSE_BUTTON1_NUM_SUBCONVERSIONS_OFFSET                            (144u)
#define CY_CAPSENSE_BUTTON1_NUM_SUBCONVERSIONS_SIZE                              (2u)
#define CY_CAPSENSE_BUTTON1_NUM_SUBCONVERSIONS_PARAM_ID                          (0x02010090u)

#define CY_CAPSENSE_BUTTON1_CDAC_REF0_VALUE                                      (cy_capsense_tuner.widgetContext[1].cdacRef[0])
#define CY_CAPSENSE_BUTTON1_CDAC_REF0_OFFSET                                     (146u)
#define CY_CAPSENSE_BUTTON1_CDAC_REF0_SIZE                                       (1u)
#define CY_CAPSENSE_BUTTON1_CDAC_REF0_PARAM_ID                                   (0x01010092u)

#define CY_CAPSENSE_BUTTON1_CDAC_REF1_VALUE                                      (cy_capsense_tuner.widgetContext[1].cdacRef[1])
#define CY_CAPSENSE_BUTTON1_CDAC_REF1_OFFSET                                     (147u)
#define CY_CAPSENSE_BUTTON1_CDAC_REF1_SIZE                                       (1u)
#define CY_CAPSENSE_BUTTON1_CDAC_REF1_PARAM_ID                                   (0x01010093u)

#define CY_CAPSENSE_BUTTON1_CDAC_REF2_VALUE                                      (cy_capsense_tuner.widgetContext[1].cdacRef[2])
#define CY_CAPSENSE_BUTTON1_CDAC_REF2_OFFSET                                     (148u)
#define CY_CAPSENSE_BUTTON1_CDAC_REF2_SIZE                                       (1u)
#define CY_CAPSENSE_BUTTON1_CDAC_REF2_PARAM_ID                                   (0x01010094u)

#define CY_CAPSENSE_BUTTON1_ROW_CDAC_REF0_VALUE                                  (cy_capsense_tuner.widgetContext[1].rowCdacRef[0])
#define CY_CAPSENSE_BUTTON1_ROW_CDAC_REF0_OFFSET                                 (149u)
#define CY_CAPSENSE_BUTTON1_ROW_CDAC_REF0_SIZE                                   (1u)
#define CY_CAPSENSE_BUTTON1_ROW_CDAC_REF0_PARAM_ID                               (0x01010095u)

#define CY_CAPSENSE_BUTTON1_ROW_CDAC_REF1_VALUE                                  (cy_capsense_tuner.widgetContext[1].rowCdacRef[1])
#define CY_CAPSENSE_BUTTON1_ROW_CDAC_REF1_OFFSET                                 (150u)
#define CY_CAPSENSE_BUTTON1_ROW_CDAC_REF1_SIZE                                   (1u)
#define CY_CAPSENSE_BUTTON1_ROW_CDAC_REF1_PARAM_ID                               (0x01010096u)

#define CY_CAPSENSE_BUTTON1_ROW_CDAC_REF2_VALUE                                  (cy_capsense_tuner.widgetContext[1].rowCdacRef[2])
#define CY_CAPSENSE_BUTTON1_ROW_CDAC_REF2_OFFSET                                 (151u)
#define CY_CAPSENSE_BUTTON1_ROW_CDAC_REF2_SIZE                                   (1u)
#define CY_CAPSENSE_BUTTON1_ROW_CDAC_REF2_PARAM_ID                               (0x01010097u)

#define CY_CAPSENSE_BUTTON1_CIC_RATE_VALUE                                       (cy_capsense_tuner.widgetContext[1].cicRate)
#define CY_CAPSENSE_BUTTON1_CIC_RATE_OFFSET                                      (152u)
#define CY_CAPSENSE_BUTTON1_CIC_RATE_SIZE                                        (1u)
#define CY_CAPSENSE_BUTTON1_CIC_RATE_PARAM_ID                                    (0x01010098u)

#define CY_CAPSENSE_BUTTON1_CDAC_DITHER_EN_VALUE                                 (cy_capsense_tuner.widgetContext[1].cdacDitherEn)
#define CY_CAPSENSE_BUTTON1_CDAC_DITHER_EN_OFFSET                                (153u)
#define CY_CAPSENSE_BUTTON1_CDAC_DITHER_EN_SIZE                                  (1u)
#define CY_CAPSENSE_BUTTON1_CDAC_DITHER_EN_PARAM_ID                              (0x01010099u)

#define CY_CAPSENSE_BUTTON1_CDAC_DITHER_VALUE_VALUE                              (cy_capsense_tuner.widgetContext[1].cdacDitherValue)
#define CY_CAPSENSE_BUTTON1_CDAC_DITHER_VALUE_OFFSET                             (154u)
#define CY_CAPSENSE_BUTTON1_CDAC_DITHER_VALUE_SIZE                               (1u)
#define CY_CAPSENSE_BUTTON1_CDAC_DITHER_VALUE_PARAM_ID                           (0x0101009au)

#define CY_CAPSENSE_BUTTON1_COARSE_INIT_BYPASS_EN_VALUE                          (cy_capsense_tuner.widgetContext[1].coarseInitBypassEn)
#define CY_CAPSENSE_BUTTON1_COARSE_INIT_BYPASS_EN_OFFSET                         (155u)
#define CY_CAPSENSE_BUTTON1_COARSE_INIT_BYPASS_EN_SIZE                           (1u)
#define CY_CAPSENSE_BUTTON1_COARSE_INIT_BYPASS_EN_PARAM_ID                       (0x0101009bu)

#define CY_CAPSENSE_BUTTON1_COMP_DIV_VALUE                                       (cy_capsense_tuner.widgetContext[1].cdacCompDivider)
#define CY_CAPSENSE_BUTTON1_COMP_DIV_OFFSET                                      (156u)
#define CY_CAPSENSE_BUTTON1_COMP_DIV_SIZE                                        (2u)
#define CY_CAPSENSE_BUTTON1_COMP_DIV_PARAM_ID                                    (0x0201009cu)

#define CY_CAPSENSE_BUTTON0_RX0_RAW0_VALUE                                       (cy_capsense_tuner.sensorContext[0].raw)
#define CY_CAPSENSE_BUTTON0_RX0_RAW0_OFFSET                                      (160u)
#define CY_CAPSENSE_BUTTON0_RX0_RAW0_SIZE                                        (2u)
#define CY_CAPSENSE_BUTTON0_RX0_RAW0_PARAM_ID                                    (0x020000a0u)

#define CY_CAPSENSE_BUTTON0_RX0_BSLN0_VALUE                                      (cy_capsense_tuner.sensorContext[0].bsln)
#define CY_CAPSENSE_BUTTON0_RX0_BSLN0_OFFSET                                     (162u)
#define CY_CAPSENSE_BUTTON0_RX0_BSLN0_SIZE                                       (2u)
#define CY_CAPSENSE_BUTTON0_RX0_BSLN0_PARAM_ID                                   (0x020000a2u)

#define CY_CAPSENSE_BUTTON0_RX0_DIFF0_VALUE                                      (cy_capsense_tuner.sensorContext[0].diff)
#define CY_CAPSENSE_BUTTON0_RX0_DIFF0_OFFSET                                     (164u)
#define CY_CAPSENSE_BUTTON0_RX0_DIFF0_SIZE                                       (2u)
#define CY_CAPSENSE_BUTTON0_RX0_DIFF0_PARAM_ID                                   (0x020000a4u)

#define CY_CAPSENSE_BUTTON0_RX0_STATUS0_VALUE                                    (cy_capsense_tuner.sensorContext[0].status)
#define CY_CAPSENSE_BUTTON0_RX0_STATUS0_OFFSET                                   (166u)
#define CY_CAPSENSE_BUTTON0_RX0_STATUS0_SIZE                                     (1u)
#define CY_CAPSENSE_BUTTON0_RX0_STATUS0_PARAM_ID                                 (0x010000a6u)

#define CY_CAPSENSE_BUTTON0_RX0_NEG_BSLN_RST_CNT0_VALUE                          (cy_capsense_tuner.sensorContext[0].negBslnRstCnt)
#define CY_CAPSENSE_BUTTON0_RX0_NEG_BSLN_RST_CNT0_OFFSET                         (167u)
#define CY_CAPSENSE_BUTTON0_RX0_NEG_BSLN_RST_CNT0_SIZE                           (1u)
#define CY_CAPSENSE_BUTTON0_RX0_NEG_BSLN_RST_CNT0_PARAM_ID                       (0x010000a7u)

#define CY_CAPSENSE_BUTTON0_RX0_BSLN_EXT0_VALUE                                  (cy_capsense_tuner.sensorContext[0].bslnExt)
#define CY_CAPSENSE_BUTTON0_RX0_BSLN_EXT0_OFFSET                                 (168u)
#define CY_CAPSENSE_BUTTON0_RX0_BSLN_EXT0_SIZE                                   (1u)
#define CY_CAPSENSE_BUTTON0_RX0_BSLN_EXT0_PARAM_ID                               (0x010000a8u)

#define CY_CAPSENSE_BUTTON0_RX0_CDAC_COMP0_VALUE                                 (cy_capsense_tuner.sensorContext[0].cdacComp)
#define CY_CAPSENSE_BUTTON0_RX0_CDAC_COMP0_OFFSET                                (169u)
#define CY_CAPSENSE_BUTTON0_RX0_CDAC_COMP0_SIZE                                  (1u)
#define CY_CAPSENSE_BUTTON0_RX0_CDAC_COMP0_PARAM_ID                              (0x010000a9u)

#define CY_CAPSENSE_BUTTON1_RX0_RAW0_VALUE                                       (cy_capsense_tuner.sensorContext[1].raw)
#define CY_CAPSENSE_BUTTON1_RX0_RAW0_OFFSET                                      (170u)
#define CY_CAPSENSE_BUTTON1_RX0_RAW0_SIZE                                        (2u)
#define CY_CAPSENSE_BUTTON1_RX0_RAW0_PARAM_ID                                    (0x020100aau)

#define CY_CAPSENSE_BUTTON1_RX0_BSLN0_VALUE                                      (cy_capsense_tuner.sensorContext[1].bsln)
#define CY_CAPSENSE_BUTTON1_RX0_BSLN0_OFFSET                                     (172u)
#define CY_CAPSENSE_BUTTON1_RX0_BSLN0_SIZE                                       (2u)
#define CY_CAPSENSE_BUTTON1_RX0_BSLN0_PARAM_ID                                   (0x020100acu)

#define CY_CAPSENSE_BUTTON1_RX0_DIFF0_VALUE                                      (cy_capsense_tuner.sensorContext[1].diff)
#define CY_CAPSENSE_BUTTON1_RX0_DIFF0_OFFSET                                     (174u)
#define CY_CAPSENSE_BUTTON1_RX0_DIFF0_SIZE                                       (2u)
#define CY_CAPSENSE_BUTTON1_RX0_DIFF0_PARAM_ID                                   (0x020100aeu)

#define CY_CAPSENSE_BUTTON1_RX0_STATUS0_VALUE                                    (cy_capsense_tuner.sensorContext[1].status)
#define CY_CAPSENSE_BUTTON1_RX0_STATUS0_OFFSET                                   (176u)
#define CY_CAPSENSE_BUTTON1_RX0_STATUS0_SIZE                                     (1u)
#define CY_CAPSENSE_BUTTON1_RX0_STATUS0_PARAM_ID                                 (0x010100b0u)

#define CY_CAPSENSE_BUTTON1_RX0_NEG_BSLN_RST_CNT0_VALUE                          (cy_capsense_tuner.sensorContext[1].negBslnRstCnt)
#define CY_CAPSENSE_BUTTON1_RX0_NEG_BSLN_RST_CNT0_OFFSET                         (177u)
#define CY_CAPSENSE_BUTTON1_RX0_NEG_BSLN_RST_CNT0_SIZE                           (1u)
#define CY_CAPSENSE_BUTTON1_RX0_NEG_BSLN_RST_CNT0_PARAM_ID                       (0x010100b1u)

#define CY_CAPSENSE_BUTTON1_RX0_BSLN_EXT0_VALUE                                  (cy_capsense_tuner.sensorContext[1].bslnExt)
#define CY_CAPSENSE_BUTTON1_RX0_BSLN_EXT0_OFFSET                                 (178u)
#define CY_CAPSENSE_BUTTON1_RX0_BSLN_EXT0_SIZE                                   (1u)
#define CY_CAPSENSE_BUTTON1_RX0_BSLN_EXT0_PARAM_ID                               (0x010100b2u)

#define CY_CAPSENSE_BUTTON1_RX0_CDAC_COMP0_VALUE                                 (cy_capsense_tuner.sensorContext[1].cdacComp)
#define CY_CAPSENSE_BUTTON1_RX0_CDAC_COMP0_OFFSET                                (179u)
#define CY_CAPSENSE_BUTTON1_RX0_CDAC_COMP0_SIZE                                  (1u)
#define CY_CAPSENSE_BUTTON1_RX0_CDAC_COMP0_PARAM_ID                              (0x010100b3u)

/* cy_capsense_context */
#define CY_CAPSENSE_COMMON_CONFIG_PTR_VALUE                                      (cy_capsense_context.ptrCommonConfig)
#define CY_CAPSENSE_COMMON_CONFIG_PTR_SIZE                                       (sizeof(cy_capsense_context.ptrCommonConfig))

#define CY_CAPSENSE_COMMON_CONTEXT_PTR_VALUE                                     (cy_capsense_context.ptrCommonContext)
#define CY_CAPSENSE_COMMON_CONTEXT_PTR_SIZE                                      (sizeof(cy_capsense_context.ptrCommonContext))

#define CY_CAPSENSE_INTERNAL_CONTEXT_PTR_VALUE                                   (cy_capsense_context.ptrInternalContext)
#define CY_CAPSENSE_INTERNAL_CONTEXT_PTR_SIZE                                    (sizeof(cy_capsense_context.ptrInternalContext))

#define CY_CAPSENSE_WD_CONFIG_PTR_VALUE                                          (cy_capsense_context.ptrWdConfig)
#define CY_CAPSENSE_WD_CONFIG_PTR_SIZE                                           (sizeof(cy_capsense_context.ptrWdConfig))

#define CY_CAPSENSE_WD_CONTEXT_PTR_VALUE                                         (cy_capsense_context.ptrWdContext)
#define CY_CAPSENSE_WD_CONTEXT_PTR_SIZE                                          (sizeof(cy_capsense_context.ptrWdContext))

#define CY_CAPSENSE_PIN_CONFIG_PTR_VALUE                                         (cy_capsense_context.ptrPinConfig)
#define CY_CAPSENSE_PIN_CONFIG_PTR_SIZE                                          (sizeof(cy_capsense_context.ptrPinConfig))

#define CY_CAPSENSE_SHIELD_PIN_CONFIG_PTR_VALUE                                  (cy_capsense_context.ptrShieldPinConfig)
#define CY_CAPSENSE_SHIELD_PIN_CONFIG_PTR_SIZE                                   (sizeof(cy_capsense_context.ptrShieldPinConfig))

#define CY_CAPSENSE_ACTIVE_SCAN_SNS_PTR_VALUE                                    (cy_capsense_context.ptrActiveScanSns)
#define CY_CAPSENSE_ACTIVE_SCAN_SNS_PTR_SIZE                                     (sizeof(cy_capsense_context.ptrActiveScanSns))

#define CY_CAPSENSE_FPTR_CONFIG_PTR_VALUE                                        (cy_capsense_context.ptrFptrConfig)
#define CY_CAPSENSE_FPTR_CONFIG_PTR_SIZE                                         (sizeof(cy_capsense_context.ptrFptrConfig))

#define CY_CAPSENSE_BIST_CONTEXT_PTR_VALUE                                       (cy_capsense_context.ptrBistContext)
#define CY_CAPSENSE_BIST_CONTEXT_PTR_SIZE                                        (sizeof(cy_capsense_context.ptrBistContext))

/* cy_capsense_commonConfig */
#define CY_CAPSENSE_CPU_CLK_HZ_VALUE                                             (cy_capsense_context.ptrCommonConfig->cpuClkHz)
#define CY_CAPSENSE_CPU_CLK_HZ_SIZE                                              (sizeof(cy_capsense_context.ptrCommonConfig->cpuClkHz))

#define CY_CAPSENSE_PERI_CLK_HZ_VALUE                                            (cy_capsense_context.ptrCommonConfig->periClkHz)
#define CY_CAPSENSE_PERI_CLK_HZ_SIZE                                             (sizeof(cy_capsense_context.ptrCommonConfig->periClkHz))

#define CY_CAPSENSE_VDDA_VALUE                                                   (cy_capsense_context.ptrCommonConfig->vdda)
#define CY_CAPSENSE_VDDA_SIZE                                                    (sizeof(cy_capsense_context.ptrCommonConfig->vdda))

#define CY_CAPSENSE_NUM_PIN_VALUE                                                (cy_capsense_context.ptrCommonConfig->numPin)
#define CY_CAPSENSE_NUM_PIN_SIZE                                                 (sizeof(cy_capsense_context.ptrCommonConfig->numPin))

#define CY_CAPSENSE_NUM_SNS_VALUE                                                (cy_capsense_context.ptrCommonConfig->numSns)
#define CY_CAPSENSE_NUM_SNS_SIZE                                                 (sizeof(cy_capsense_context.ptrCommonConfig->numSns))

#define CY_CAPSENSE_NUM_WD_VALUE                                                 (cy_capsense_context.ptrCommonConfig->numWd)
#define CY_CAPSENSE_NUM_WD_SIZE                                                  (sizeof(cy_capsense_context.ptrCommonConfig->numWd))

#define CY_CAPSENSE_CSD_EN_VALUE                                                 (cy_capsense_context.ptrCommonConfig->csdEn)
#define CY_CAPSENSE_CSD_EN_SIZE                                                  (sizeof(cy_capsense_context.ptrCommonConfig->csdEn))

#define CY_CAPSENSE_CSX_EN_VALUE                                                 (cy_capsense_context.ptrCommonConfig->csxEn)
#define CY_CAPSENSE_CSX_EN_SIZE                                                  (sizeof(cy_capsense_context.ptrCommonConfig->csxEn))

#define CY_CAPSENSE_MFS_EN_VALUE                                                 (cy_capsense_context.ptrCommonConfig->mfsEn)
#define CY_CAPSENSE_MFS_EN_SIZE                                                  (sizeof(cy_capsense_context.ptrCommonConfig->mfsEn))

#define CY_CAPSENSE_BIST_EN_VALUE                                                (cy_capsense_context.ptrCommonConfig->bistEn)
#define CY_CAPSENSE_BIST_EN_SIZE                                                 (sizeof(cy_capsense_context.ptrCommonConfig->bistEn))

#define CY_CAPSENSE_POSITION_FILTER_EN_VALUE                                     (cy_capsense_context.ptrCommonConfig->positionFilterEn)
#define CY_CAPSENSE_POSITION_FILTER_EN_SIZE                                      (sizeof(cy_capsense_context.ptrCommonConfig->positionFilterEn))

#define CY_CAPSENSE_PERI_DIVIDER_TYPE_VALUE                                      (cy_capsense_context.ptrCommonConfig->periDividerType)
#define CY_CAPSENSE_PERI_DIVIDER_TYPE_SIZE                                       (sizeof(cy_capsense_context.ptrCommonConfig->periDividerType))

#define CY_CAPSENSE_PERI_DIVIDER_INDEX_VALUE                                     (cy_capsense_context.ptrCommonConfig->periDividerIndex)
#define CY_CAPSENSE_PERI_DIVIDER_INDEX_SIZE                                      (sizeof(cy_capsense_context.ptrCommonConfig->periDividerIndex))

#define CY_CAPSENSE_ANALOG_WAKEUP_DELAY_VALUE                                    (cy_capsense_context.ptrCommonConfig->analogWakeupDelay)
#define CY_CAPSENSE_ANALOG_WAKEUP_DELAY_SIZE                                     (sizeof(cy_capsense_context.ptrCommonConfig->analogWakeupDelay))

#define CY_CAPSENSE_PROX_TOUCH_COEFF_VALUE                                       (cy_capsense_context.ptrCommonConfig->proxTouchCoeff)
#define CY_CAPSENSE_PROX_TOUCH_COEFF_SIZE                                        (sizeof(cy_capsense_context.ptrCommonConfig->proxTouchCoeff))

#define CY_CAPSENSE_SW_SENSOR_AUTO_RESET_EN_VALUE                                (cy_capsense_context.ptrCommonConfig->swSensorAutoResetEn)
#define CY_CAPSENSE_SW_SENSOR_AUTO_RESET_EN_SIZE                                 (sizeof(cy_capsense_context.ptrCommonConfig->swSensorAutoResetEn))

#define CY_CAPSENSE_CSD_INACTIVE_SNS_CONNECTION_VALUE                            (cy_capsense_context.ptrCommonConfig->csdInactiveSnsConnection)
#define CY_CAPSENSE_CSD_INACTIVE_SNS_CONNECTION_SIZE                             (sizeof(cy_capsense_context.ptrCommonConfig->csdInactiveSnsConnection))

#define CY_CAPSENSE_CSD_R_CONST_VALUE                                            (cy_capsense_context.ptrCommonConfig->csdRConst)
#define CY_CAPSENSE_CSD_R_CONST_SIZE                                             (sizeof(cy_capsense_context.ptrCommonConfig->csdRConst))

#define CY_CAPSENSE_CSD_SHIELD_NUM_PIN_VALUE                                     (cy_capsense_context.ptrCommonConfig->csdShieldNumPin)
#define CY_CAPSENSE_CSD_SHIELD_NUM_PIN_SIZE                                      (sizeof(cy_capsense_context.ptrCommonConfig->csdShieldNumPin))

#define CY_CAPSENSE_CSD_RAW_TARGET_VALUE                                         (cy_capsense_context.ptrCommonConfig->csdRawTarget)
#define CY_CAPSENSE_CSD_RAW_TARGET_SIZE                                          (sizeof(cy_capsense_context.ptrCommonConfig->csdRawTarget))

#define CY_CAPSENSE_CSD_AUTOTUNE_EN_VALUE                                        (cy_capsense_context.ptrCommonConfig->csdAutotuneEn)
#define CY_CAPSENSE_CSD_AUTOTUNE_EN_SIZE                                         (sizeof(cy_capsense_context.ptrCommonConfig->csdAutotuneEn))

#define CY_CAPSENSE_CSD_CALIBRATION_ERROR_VALUE                                  (cy_capsense_context.ptrCommonConfig->csdCalibrationError)
#define CY_CAPSENSE_CSD_CALIBRATION_ERROR_SIZE                                   (sizeof(cy_capsense_context.ptrCommonConfig->csdCalibrationError))

#define CY_CAPSENSE_CSD_MFS_DIVIDER_OFFSET_F1_VALUE                              (cy_capsense_context.ptrCommonConfig->csdMfsDividerOffsetF1)
#define CY_CAPSENSE_CSD_MFS_DIVIDER_OFFSET_F1_SIZE                               (sizeof(cy_capsense_context.ptrCommonConfig->csdMfsDividerOffsetF1))

#define CY_CAPSENSE_CSD_MFS_DIVIDER_OFFSET_F2_VALUE                              (cy_capsense_context.ptrCommonConfig->csdMfsDividerOffsetF2)
#define CY_CAPSENSE_CSD_MFS_DIVIDER_OFFSET_F2_SIZE                               (sizeof(cy_capsense_context.ptrCommonConfig->csdMfsDividerOffsetF2))

#define CY_CAPSENSE_CSX_RAW_TARGET_VALUE                                         (cy_capsense_context.ptrCommonConfig->csxRawTarget)
#define CY_CAPSENSE_CSX_RAW_TARGET_SIZE                                          (sizeof(cy_capsense_context.ptrCommonConfig->csxRawTarget))

#define CY_CAPSENSE_CSX_CALIBRATION_ERROR_VALUE                                  (cy_capsense_context.ptrCommonConfig->csxCalibrationError)
#define CY_CAPSENSE_CSX_CALIBRATION_ERROR_SIZE                                   (sizeof(cy_capsense_context.ptrCommonConfig->csxCalibrationError))

#define CY_CAPSENSE_CSX_MFS_DIVIDER_OFFSET_F1_VALUE                              (cy_capsense_context.ptrCommonConfig->csxMfsDividerOffsetF1)
#define CY_CAPSENSE_CSX_MFS_DIVIDER_OFFSET_F1_SIZE                               (sizeof(cy_capsense_context.ptrCommonConfig->csxMfsDividerOffsetF1))

#define CY_CAPSENSE_CSX_MFS_DIVIDER_OFFSET_F2_VALUE                              (cy_capsense_context.ptrCommonConfig->csxMfsDividerOffsetF2)
#define CY_CAPSENSE_CSX_MFS_DIVIDER_OFFSET_F2_SIZE                               (sizeof(cy_capsense_context.ptrCommonConfig->csxMfsDividerOffsetF2))

#define CY_CAPSENSE_PTR_MSC_CH_CONFIG_VALUE                                      (cy_capsense_context.ptrCommonConfig->ptrMscChConfig)
#define CY_CAPSENSE_PTR_MSC_CH_CONFIG_SIZE                                       (sizeof(cy_capsense_context.ptrCommonConfig->ptrMscChConfig))

#define CY_CAPSENSE_PTR_DMAC_BASE_VALUE                                          (cy_capsense_context.ptrCommonConfig->ptrDmacBase)
#define CY_CAPSENSE_PTR_DMAC_BASE_SIZE                                           (sizeof(cy_capsense_context.ptrCommonConfig->ptrDmacBase))

#define CY_CAPSENSE_PTR_DMA_WR_CH_SNS_CFG_ADDR_VALUE                             (cy_capsense_context.ptrCommonConfig->ptrDmaWrChSnsCfgAddr)
#define CY_CAPSENSE_PTR_DMA_WR_CH_SNS_CFG_ADDR_SIZE                              (sizeof(cy_capsense_context.ptrCommonConfig->ptrDmaWrChSnsCfgAddr))

#define CY_CAPSENSE_PTR_DMA_RD_CH_SNS_CFG_ADDR_VALUE                             (cy_capsense_context.ptrCommonConfig->ptrDmaRdChSnsCfgAddr)
#define CY_CAPSENSE_PTR_DMA_RD_CH_SNS_CFG_ADDR_SIZE                              (sizeof(cy_capsense_context.ptrCommonConfig->ptrDmaRdChSnsCfgAddr))

#define CY_CAPSENSE_CSD_SHIELD_MODE_VALUE                                        (cy_capsense_context.ptrCommonConfig->csdShieldMode)
#define CY_CAPSENSE_CSD_SHIELD_MODE_SIZE                                         (sizeof(cy_capsense_context.ptrCommonConfig->csdShieldMode))

#define CY_CAPSENSE_SENSOR_CONNECTION_VALUE                                      (cy_capsense_context.ptrCommonConfig->sensorConnection)
#define CY_CAPSENSE_SENSOR_CONNECTION_SIZE                                       (sizeof(cy_capsense_context.ptrCommonConfig->sensorConnection))

#define CY_CAPSENSE_CSD_CDAC_AUTOCAL_EN_VALUE                                    (cy_capsense_context.ptrCommonConfig->csdCdacAutocalEn)
#define CY_CAPSENSE_CSD_CDAC_AUTOCAL_EN_SIZE                                     (sizeof(cy_capsense_context.ptrCommonConfig->csdCdacAutocalEn))

#define CY_CAPSENSE_CSD_CDAC_COMP_EN_VALUE                                       (cy_capsense_context.ptrCommonConfig->csdCdacCompEn)
#define CY_CAPSENSE_CSD_CDAC_COMP_EN_SIZE                                        (sizeof(cy_capsense_context.ptrCommonConfig->csdCdacCompEn))

#define CY_CAPSENSE_CSX_CDAC_AUTOCAL_EN_VALUE                                    (cy_capsense_context.ptrCommonConfig->csxCdacAutocalEn)
#define CY_CAPSENSE_CSX_CDAC_AUTOCAL_EN_SIZE                                     (sizeof(cy_capsense_context.ptrCommonConfig->csxCdacAutocalEn))

#define CY_CAPSENSE_CSX_CDAC_COMP_EN_VALUE                                       (cy_capsense_context.ptrCommonConfig->csxCdacCompEn)
#define CY_CAPSENSE_CSX_CDAC_COMP_EN_SIZE                                        (sizeof(cy_capsense_context.ptrCommonConfig->csxCdacCompEn))

#define CY_CAPSENSE_CSX_AUTOTUNE_EN_VALUE                                        (cy_capsense_context.ptrCommonConfig->csxAutotuneEn)
#define CY_CAPSENSE_CSX_AUTOTUNE_EN_SIZE                                         (sizeof(cy_capsense_context.ptrCommonConfig->csxAutotuneEn))

#define CY_CAPSENSE_SCANNING_MODE_VALUE                                          (cy_capsense_context.ptrCommonConfig->scanningMode)
#define CY_CAPSENSE_SCANNING_MODE_SIZE                                           (sizeof(cy_capsense_context.ptrCommonConfig->scanningMode))

#define CY_CAPSENSE_MPTX_EN_VALUE                                                (cy_capsense_context.ptrCommonConfig->mptxEn)
#define CY_CAPSENSE_MPTX_EN_SIZE                                                 (sizeof(cy_capsense_context.ptrCommonConfig->mptxEn))

#define CY_CAPSENSE_NUM_EPI_CYCLES_VALUE                                         (cy_capsense_context.ptrCommonConfig->numEpiCycles)
#define CY_CAPSENSE_NUM_EPI_CYCLES_SIZE                                          (sizeof(cy_capsense_context.ptrCommonConfig->numEpiCycles))

#define CY_CAPSENSE_CHOP_POLARITY_VALUE                                          (cy_capsense_context.ptrCommonConfig->chopPolarity)
#define CY_CAPSENSE_CHOP_POLARITY_SIZE                                           (sizeof(cy_capsense_context.ptrCommonConfig->chopPolarity))

#define CY_CAPSENSE_NUM_COARSE_INIT_CHARGE_CYCLES_VALUE                          (cy_capsense_context.ptrCommonConfig->numCoarseInitChargeCycles)
#define CY_CAPSENSE_NUM_COARSE_INIT_CHARGE_CYCLES_SIZE                           (sizeof(cy_capsense_context.ptrCommonConfig->numCoarseInitChargeCycles))

#define CY_CAPSENSE_NUM_COARSE_INIT_SETTLE_CYCLES_VALUE                          (cy_capsense_context.ptrCommonConfig->numCoarseInitSettleCycles)
#define CY_CAPSENSE_NUM_COARSE_INIT_SETTLE_CYCLES_SIZE                           (sizeof(cy_capsense_context.ptrCommonConfig->numCoarseInitSettleCycles))

#define CY_CAPSENSE_CIC_FILTER_MODE_VALUE                                        (cy_capsense_context.ptrCommonConfig->cicFilterMode)
#define CY_CAPSENSE_CIC_FILTER_MODE_SIZE                                         (sizeof(cy_capsense_context.ptrCommonConfig->cicFilterMode))

#define CY_CAPSENSE_NUM_BAD_SCANS_VALUE                                          (cy_capsense_context.ptrCommonConfig->numBadScans)
#define CY_CAPSENSE_NUM_BAD_SCANS_SIZE                                           (sizeof(cy_capsense_context.ptrCommonConfig->numBadScans))

#define CY_CAPSENSE_COUNTER_MODE_VALUE                                           (cy_capsense_context.ptrCommonConfig->counterMode)
#define CY_CAPSENSE_COUNTER_MODE_SIZE                                            (sizeof(cy_capsense_context.ptrCommonConfig->counterMode))

#define CY_CAPSENSE_SYNC_FRAME_START_EN_VALUE                                    (cy_capsense_context.ptrCommonConfig->syncFrameStartEn)
#define CY_CAPSENSE_SYNC_FRAME_START_EN_SIZE                                     (sizeof(cy_capsense_context.ptrCommonConfig->syncFrameStartEn))

#define CY_CAPSENSE_SYNC_CLOCK_EN_VALUE                                          (cy_capsense_context.ptrCommonConfig->syncClockEn)
#define CY_CAPSENSE_SYNC_CLOCK_EN_SIZE                                           (sizeof(cy_capsense_context.ptrCommonConfig->syncClockEn))

#define CY_CAPSENSE_SYNC_MODE_VALUE                                              (cy_capsense_context.ptrCommonConfig->syncMode)
#define CY_CAPSENSE_SYNC_MODE_SIZE                                               (sizeof(cy_capsense_context.ptrCommonConfig->syncMode))

#define CY_CAPSENSE_NUM_CHIPS_VALUE                                              (cy_capsense_context.ptrCommonConfig->numChips)
#define CY_CAPSENSE_NUM_CHIPS_SIZE                                               (sizeof(cy_capsense_context.ptrCommonConfig->numChips))

#define CY_CAPSENSE_NUM_CHANNELS_VALUE                                           (cy_capsense_context.ptrCommonConfig->numChannels)
#define CY_CAPSENSE_NUM_CHANNELS_SIZE                                            (sizeof(cy_capsense_context.ptrCommonConfig->numChannels))

#define CY_CAPSENSE_NUM_SLOTS_VALUE                                              (cy_capsense_context.ptrCommonConfig->numSlots)
#define CY_CAPSENSE_NUM_SLOTS_SIZE                                               (sizeof(cy_capsense_context.ptrCommonConfig->numSlots))

#define CY_CAPSENSE_CHANNEL_OFFSET_VALUE                                         (cy_capsense_context.ptrCommonConfig->channelOffset)
#define CY_CAPSENSE_CHANNEL_OFFSET_SIZE                                          (sizeof(cy_capsense_context.ptrCommonConfig->channelOffset))

/* cy_capsense_widgetConfig */
#define CY_CAPSENSE_BUTTON0_PTR_WD_CONTEXT_VALUE                                 (cy_capsense_context.ptrWdConfig[0u].ptrWdContext)
#define CY_CAPSENSE_BUTTON0_PTR_WD_CONTEXT_SIZE                                  (sizeof(cy_capsense_context.ptrWdConfig[0u].ptrWdContext))
#define CY_CAPSENSE_BUTTON0_PTR_SNS_CONTEXT_VALUE                                (cy_capsense_context.ptrWdConfig[0u].ptrSnsContext)
#define CY_CAPSENSE_BUTTON0_PTR_SNS_CONTEXT_SIZE                                 (sizeof(cy_capsense_context.ptrWdConfig[0u].ptrSnsContext))
#define CY_CAPSENSE_BUTTON0_PTR_ELTD_CONTEXT_VALUE                               (cy_capsense_context.ptrWdConfig[0u].ptrEltdConfig)
#define CY_CAPSENSE_BUTTON0_PTR_ELTD_CONTEXT_SIZE                                (sizeof(cy_capsense_context.ptrWdConfig[0u].ptrEltdConfig))
#define CY_CAPSENSE_BUTTON0_PTR_NOISE_ENVELOPE_VALUE                             (cy_capsense_context.ptrWdConfig[0u].ptrNoiseEnvelope)
#define CY_CAPSENSE_BUTTON0_PTR_NOISE_ENVELOPE_SIZE                              (sizeof(cy_capsense_context.ptrWdConfig[0u].ptrNoiseEnvelope))
#define CY_CAPSENSE_BUTTON0_PTR_RAW_FILTER_HISTORY_VALUE                         (cy_capsense_context.ptrWdConfig[0u].ptrRawFilterHistory)
#define CY_CAPSENSE_BUTTON0_PTR_RAW_FILTER_HISTORY_SIZE                          (sizeof(cy_capsense_context.ptrWdConfig[0u].ptrRawFilterHistory))
#define CY_CAPSENSE_BUTTON0_PTR_RAW_FILTER_HISTORY_LOW_VALUE                     (cy_capsense_context.ptrWdConfig[0u].ptrRawFilterHistoryLow)
#define CY_CAPSENSE_BUTTON0_PTR_RAW_FILTER_HISTORY_LOW_SIZE                      (sizeof(cy_capsense_context.ptrWdConfig[0u].ptrRawFilterHistoryLow))
#define CY_CAPSENSE_BUTTON0_IIR_COEFF_VALUE                                      (cy_capsense_context.ptrWdConfig[0u].iirCoeff)
#define CY_CAPSENSE_BUTTON0_IIR_COEFF_SIZE                                       (sizeof(cy_capsense_context.ptrWdConfig[0u].iirCoeff))
#define CY_CAPSENSE_BUTTON0_PTR_DEBOUNCE_ARR_VALUE                               (cy_capsense_context.ptrWdConfig[0u].ptrDebounceArr)
#define CY_CAPSENSE_BUTTON0_PTR_DEBOUNCE_ARR_SIZE                                (sizeof(cy_capsense_context.ptrWdConfig[0u].ptrDebounceArr))
#define CY_CAPSENSE_BUTTON0_PTR_DIPLEX_TABLE_VALUE                               (cy_capsense_context.ptrWdConfig[0u].ptrDiplexTable)
#define CY_CAPSENSE_BUTTON0_PTR_DIPLEX_TABLE_SIZE                                (sizeof(cy_capsense_context.ptrWdConfig[0u].ptrDiplexTable))
#define CY_CAPSENSE_BUTTON0_CENTROID_CONFIG_VALUE                                (cy_capsense_context.ptrWdConfig[0u].centroidConfig)
#define CY_CAPSENSE_BUTTON0_CENTROID_CONFIG_SIZE                                 (sizeof(cy_capsense_context.ptrWdConfig[0u].centroidConfig))
#define CY_CAPSENSE_BUTTON0_X_RESOLUTION_VALUE                                   (cy_capsense_context.ptrWdConfig[0u].xResolution)
#define CY_CAPSENSE_BUTTON0_X_RESOLUTION_SIZE                                    (sizeof(cy_capsense_context.ptrWdConfig[0u].xResolution))
#define CY_CAPSENSE_BUTTON0_Y_RESOLUTION_VALUE                                   (cy_capsense_context.ptrWdConfig[0u].yResolution)
#define CY_CAPSENSE_BUTTON0_Y_RESOLUTION_SIZE                                    (sizeof(cy_capsense_context.ptrWdConfig[0u].yResolution))
#define CY_CAPSENSE_BUTTON0_NUM_SNS_VALUE                                        (cy_capsense_context.ptrWdConfig[0u].numSns)
#define CY_CAPSENSE_BUTTON0_NUM_SNS_SIZE                                         (sizeof(cy_capsense_context.ptrWdConfig[0u].numSns))
#define CY_CAPSENSE_BUTTON0_NUM_COLS_VALUE                                       (cy_capsense_context.ptrWdConfig[0u].numCols)
#define CY_CAPSENSE_BUTTON0_NUM_COLS_SIZE                                        (sizeof(cy_capsense_context.ptrWdConfig[0u].numCols))
#define CY_CAPSENSE_BUTTON0_NUM_ROWS_VALUE                                       (cy_capsense_context.ptrWdConfig[0u].numRows)
#define CY_CAPSENSE_BUTTON0_NUM_ROWS_SIZE                                        (sizeof(cy_capsense_context.ptrWdConfig[0u].numRows))
#define CY_CAPSENSE_BUTTON0_PTR_POS_FILTER_HISTORY_VALUE                         (cy_capsense_context.ptrWdConfig[0u].ptrPosFilterHistory)
#define CY_CAPSENSE_BUTTON0_PTR_POS_FILTER_HISTORY_SIZE                          (sizeof(cy_capsense_context.ptrWdConfig[0u].ptrPosFilterHistory))
#define CY_CAPSENSE_BUTTON0_PTR_CSX_TOUCH_HISTORY_VALUE                          (cy_capsense_context.ptrWdConfig[0u].ptrCsxTouchHistory)
#define CY_CAPSENSE_BUTTON0_PTR_CSX_TOUCH_HISTORY_SIZE                           (sizeof(cy_capsense_context.ptrWdConfig[0u].ptrCsxTouchHistory))
#define CY_CAPSENSE_BUTTON0_PTR_CSX_TOUCH_BUFFER_VALUE                           (cy_capsense_context.ptrWdConfig[0u].ptrCsxTouchBuffer)
#define CY_CAPSENSE_BUTTON0_PTR_CSX_TOUCH_BUFFER_SIZE                            (sizeof(cy_capsense_context.ptrWdConfig[0u].ptrCsxTouchBuffer))
#define CY_CAPSENSE_BUTTON0_PTR_CSD_TOUCH_BUFFER_VALUE                           (cy_capsense_context.ptrWdConfig[0u].ptrCsdTouchBuffer)
#define CY_CAPSENSE_BUTTON0_PTR_CSD_TOUCH_BUFFER_SIZE                            (sizeof(cy_capsense_context.ptrWdConfig[0u].ptrCsdTouchBuffer))
#define CY_CAPSENSE_BUTTON0_PTR_GESTURE_CONFIG_VALUE                             (cy_capsense_context.ptrWdConfig[0u].ptrGestureConfig)
#define CY_CAPSENSE_BUTTON0_PTR_GESTURE_CONFIG_SIZE                              (sizeof(cy_capsense_context.ptrWdConfig[0u].ptrGestureConfig))
#define CY_CAPSENSE_BUTTON0_PTR_GESTURE_CONTEXT_VALUE                            (cy_capsense_context.ptrWdConfig[0u].ptrGestureContext)
#define CY_CAPSENSE_BUTTON0_PTR_GESTURE_CONTEXT_SIZE                             (sizeof(cy_capsense_context.ptrWdConfig[0u].ptrGestureContext))
#define CY_CAPSENSE_BUTTON0_BALLISTIC_CONFIG_VALUE                               (cy_capsense_context.ptrWdConfig[0u].ballisticConfig)
#define CY_CAPSENSE_BUTTON0_BALLISTIC_CONFIG_SIZE                                (sizeof(cy_capsense_context.ptrWdConfig[0u].ballisticConfig))
#define CY_CAPSENSE_BUTTON0_PTR_BALLISTIC_CONTEXT_VALUE                          (cy_capsense_context.ptrWdConfig[0u].ptrBallisticContext)
#define CY_CAPSENSE_BUTTON0_PTR_BALLISTIC_CONTEXT_SIZE                           (sizeof(cy_capsense_context.ptrWdConfig[0u].ptrBallisticContext))
#define CY_CAPSENSE_BUTTON0_AIIR_CONFIG_VALUE                                    (cy_capsense_context.ptrWdConfig[0u].aiirConfig)
#define CY_CAPSENSE_BUTTON0_AIIR_CONFIG_SIZE                                     (sizeof(cy_capsense_context.ptrWdConfig[0u].aiirConfig))
#define CY_CAPSENSE_BUTTON0_ADV_CONFIG_VALUE                                     (cy_capsense_context.ptrWdConfig[0u].advConfig)
#define CY_CAPSENSE_BUTTON0_ADV_CONFIG_SIZE                                      (sizeof(cy_capsense_context.ptrWdConfig[0u].advConfig))
#define CY_CAPSENSE_BUTTON0_POS_FILTER_CONFIG_VALUE                              (cy_capsense_context.ptrWdConfig[0u].posFilterConfig)
#define CY_CAPSENSE_BUTTON0_POS_FILTER_CONFIG_SIZE                               (sizeof(cy_capsense_context.ptrWdConfig[0u].posFilterConfig))
#define CY_CAPSENSE_BUTTON0_RAW_FILTER_CONFIG_VALUE                              (cy_capsense_context.ptrWdConfig[0u].rawFilterConfig)
#define CY_CAPSENSE_BUTTON0_RAW_FILTER_CONFIG_SIZE                               (sizeof(cy_capsense_context.ptrWdConfig[0u].rawFilterConfig))
#define CY_CAPSENSE_BUTTON0_SENSE_METHOD_VALUE                                   (cy_capsense_context.ptrWdConfig[0u].senseMethod)
#define CY_CAPSENSE_BUTTON0_SENSE_METHOD_SIZE                                    (sizeof(cy_capsense_context.ptrWdConfig[0u].senseMethod))
#define CY_CAPSENSE_BUTTON0_WD_TYPE_VALUE                                        (cy_capsense_context.ptrWdConfig[0u].wdType)
#define CY_CAPSENSE_BUTTON0_WD_TYPE_SIZE                                         (sizeof(cy_capsense_context.ptrWdConfig[0u].wdType))

#define CY_CAPSENSE_BUTTON1_PTR_WD_CONTEXT_VALUE                                 (cy_capsense_context.ptrWdConfig[1u].ptrWdContext)
#define CY_CAPSENSE_BUTTON1_PTR_WD_CONTEXT_SIZE                                  (sizeof(cy_capsense_context.ptrWdConfig[1u].ptrWdContext))
#define CY_CAPSENSE_BUTTON1_PTR_SNS_CONTEXT_VALUE                                (cy_capsense_context.ptrWdConfig[1u].ptrSnsContext)
#define CY_CAPSENSE_BUTTON1_PTR_SNS_CONTEXT_SIZE                                 (sizeof(cy_capsense_context.ptrWdConfig[1u].ptrSnsContext))
#define CY_CAPSENSE_BUTTON1_PTR_ELTD_CONTEXT_VALUE                               (cy_capsense_context.ptrWdConfig[1u].ptrEltdConfig)
#define CY_CAPSENSE_BUTTON1_PTR_ELTD_CONTEXT_SIZE                                (sizeof(cy_capsense_context.ptrWdConfig[1u].ptrEltdConfig))
#define CY_CAPSENSE_BUTTON1_PTR_NOISE_ENVELOPE_VALUE                             (cy_capsense_context.ptrWdConfig[1u].ptrNoiseEnvelope)
#define CY_CAPSENSE_BUTTON1_PTR_NOISE_ENVELOPE_SIZE                              (sizeof(cy_capsense_context.ptrWdConfig[1u].ptrNoiseEnvelope))
#define CY_CAPSENSE_BUTTON1_PTR_RAW_FILTER_HISTORY_VALUE                         (cy_capsense_context.ptrWdConfig[1u].ptrRawFilterHistory)
#define CY_CAPSENSE_BUTTON1_PTR_RAW_FILTER_HISTORY_SIZE                          (sizeof(cy_capsense_context.ptrWdConfig[1u].ptrRawFilterHistory))
#define CY_CAPSENSE_BUTTON1_PTR_RAW_FILTER_HISTORY_LOW_VALUE                     (cy_capsense_context.ptrWdConfig[1u].ptrRawFilterHistoryLow)
#define CY_CAPSENSE_BUTTON1_PTR_RAW_FILTER_HISTORY_LOW_SIZE                      (sizeof(cy_capsense_context.ptrWdConfig[1u].ptrRawFilterHistoryLow))
#define CY_CAPSENSE_BUTTON1_IIR_COEFF_VALUE                                      (cy_capsense_context.ptrWdConfig[1u].iirCoeff)
#define CY_CAPSENSE_BUTTON1_IIR_COEFF_SIZE                                       (sizeof(cy_capsense_context.ptrWdConfig[1u].iirCoeff))
#define CY_CAPSENSE_BUTTON1_PTR_DEBOUNCE_ARR_VALUE                               (cy_capsense_context.ptrWdConfig[1u].ptrDebounceArr)
#define CY_CAPSENSE_BUTTON1_PTR_DEBOUNCE_ARR_SIZE                                (sizeof(cy_capsense_context.ptrWdConfig[1u].ptrDebounceArr))
#define CY_CAPSENSE_BUTTON1_PTR_DIPLEX_TABLE_VALUE                               (cy_capsense_context.ptrWdConfig[1u].ptrDiplexTable)
#define CY_CAPSENSE_BUTTON1_PTR_DIPLEX_TABLE_SIZE                                (sizeof(cy_capsense_context.ptrWdConfig[1u].ptrDiplexTable))
#define CY_CAPSENSE_BUTTON1_CENTROID_CONFIG_VALUE                                (cy_capsense_context.ptrWdConfig[1u].centroidConfig)
#define CY_CAPSENSE_BUTTON1_CENTROID_CONFIG_SIZE                                 (sizeof(cy_capsense_context.ptrWdConfig[1u].centroidConfig))
#define CY_CAPSENSE_BUTTON1_X_RESOLUTION_VALUE                                   (cy_capsense_context.ptrWdConfig[1u].xResolution)
#define CY_CAPSENSE_BUTTON1_X_RESOLUTION_SIZE                                    (sizeof(cy_capsense_context.ptrWdConfig[1u].xResolution))
#define CY_CAPSENSE_BUTTON1_Y_RESOLUTION_VALUE                                   (cy_capsense_context.ptrWdConfig[1u].yResolution)
#define CY_CAPSENSE_BUTTON1_Y_RESOLUTION_SIZE                                    (sizeof(cy_capsense_context.ptrWdConfig[1u].yResolution))
#define CY_CAPSENSE_BUTTON1_NUM_SNS_VALUE                                        (cy_capsense_context.ptrWdConfig[1u].numSns)
#define CY_CAPSENSE_BUTTON1_NUM_SNS_SIZE                                         (sizeof(cy_capsense_context.ptrWdConfig[1u].numSns))
#define CY_CAPSENSE_BUTTON1_NUM_COLS_VALUE                                       (cy_capsense_context.ptrWdConfig[1u].numCols)
#define CY_CAPSENSE_BUTTON1_NUM_COLS_SIZE                                        (sizeof(cy_capsense_context.ptrWdConfig[1u].numCols))
#define CY_CAPSENSE_BUTTON1_NUM_ROWS_VALUE                                       (cy_capsense_context.ptrWdConfig[1u].numRows)
#define CY_CAPSENSE_BUTTON1_NUM_ROWS_SIZE                                        (sizeof(cy_capsense_context.ptrWdConfig[1u].numRows))
#define CY_CAPSENSE_BUTTON1_PTR_POS_FILTER_HISTORY_VALUE                         (cy_capsense_context.ptrWdConfig[1u].ptrPosFilterHistory)
#define CY_CAPSENSE_BUTTON1_PTR_POS_FILTER_HISTORY_SIZE                          (sizeof(cy_capsense_context.ptrWdConfig[1u].ptrPosFilterHistory))
#define CY_CAPSENSE_BUTTON1_PTR_CSX_TOUCH_HISTORY_VALUE                          (cy_capsense_context.ptrWdConfig[1u].ptrCsxTouchHistory)
#define CY_CAPSENSE_BUTTON1_PTR_CSX_TOUCH_HISTORY_SIZE                           (sizeof(cy_capsense_context.ptrWdConfig[1u].ptrCsxTouchHistory))
#define CY_CAPSENSE_BUTTON1_PTR_CSX_TOUCH_BUFFER_VALUE                           (cy_capsense_context.ptrWdConfig[1u].ptrCsxTouchBuffer)
#define CY_CAPSENSE_BUTTON1_PTR_CSX_TOUCH_BUFFER_SIZE                            (sizeof(cy_capsense_context.ptrWdConfig[1u].ptrCsxTouchBuffer))
#define CY_CAPSENSE_BUTTON1_PTR_CSD_TOUCH_BUFFER_VALUE                           (cy_capsense_context.ptrWdConfig[1u].ptrCsdTouchBuffer)
#define CY_CAPSENSE_BUTTON1_PTR_CSD_TOUCH_BUFFER_SIZE                            (sizeof(cy_capsense_context.ptrWdConfig[1u].ptrCsdTouchBuffer))
#define CY_CAPSENSE_BUTTON1_PTR_GESTURE_CONFIG_VALUE                             (cy_capsense_context.ptrWdConfig[1u].ptrGestureConfig)
#define CY_CAPSENSE_BUTTON1_PTR_GESTURE_CONFIG_SIZE                              (sizeof(cy_capsense_context.ptrWdConfig[1u].ptrGestureConfig))
#define CY_CAPSENSE_BUTTON1_PTR_GESTURE_CONTEXT_VALUE                            (cy_capsense_context.ptrWdConfig[1u].ptrGestureContext)
#define CY_CAPSENSE_BUTTON1_PTR_GESTURE_CONTEXT_SIZE                             (sizeof(cy_capsense_context.ptrWdConfig[1u].ptrGestureContext))
#define CY_CAPSENSE_BUTTON1_BALLISTIC_CONFIG_VALUE                               (cy_capsense_context.ptrWdConfig[1u].ballisticConfig)
#define CY_CAPSENSE_BUTTON1_BALLISTIC_CONFIG_SIZE                                (sizeof(cy_capsense_context.ptrWdConfig[1u].ballisticConfig))
#define CY_CAPSENSE_BUTTON1_PTR_BALLISTIC_CONTEXT_VALUE                          (cy_capsense_context.ptrWdConfig[1u].ptrBallisticContext)
#define CY_CAPSENSE_BUTTON1_PTR_BALLISTIC_CONTEXT_SIZE                           (sizeof(cy_capsense_context.ptrWdConfig[1u].ptrBallisticContext))
#define CY_CAPSENSE_BUTTON1_AIIR_CONFIG_VALUE                                    (cy_capsense_context.ptrWdConfig[1u].aiirConfig)
#define CY_CAPSENSE_BUTTON1_AIIR_CONFIG_SIZE                                     (sizeof(cy_capsense_context.ptrWdConfig[1u].aiirConfig))
#define CY_CAPSENSE_BUTTON1_ADV_CONFIG_VALUE                                     (cy_capsense_context.ptrWdConfig[1u].advConfig)
#define CY_CAPSENSE_BUTTON1_ADV_CONFIG_SIZE                                      (sizeof(cy_capsense_context.ptrWdConfig[1u].advConfig))
#define CY_CAPSENSE_BUTTON1_POS_FILTER_CONFIG_VALUE                              (cy_capsense_context.ptrWdConfig[1u].posFilterConfig)
#define CY_CAPSENSE_BUTTON1_POS_FILTER_CONFIG_SIZE                               (sizeof(cy_capsense_context.ptrWdConfig[1u].posFilterConfig))
#define CY_CAPSENSE_BUTTON1_RAW_FILTER_CONFIG_VALUE                              (cy_capsense_context.ptrWdConfig[1u].rawFilterConfig)
#define CY_CAPSENSE_BUTTON1_RAW_FILTER_CONFIG_SIZE                               (sizeof(cy_capsense_context.ptrWdConfig[1u].rawFilterConfig))
#define CY_CAPSENSE_BUTTON1_SENSE_METHOD_VALUE                                   (cy_capsense_context.ptrWdConfig[1u].senseMethod)
#define CY_CAPSENSE_BUTTON1_SENSE_METHOD_SIZE                                    (sizeof(cy_capsense_context.ptrWdConfig[1u].senseMethod))
#define CY_CAPSENSE_BUTTON1_WD_TYPE_VALUE                                        (cy_capsense_context.ptrWdConfig[1u].wdType)
#define CY_CAPSENSE_BUTTON1_WD_TYPE_SIZE                                         (sizeof(cy_capsense_context.ptrWdConfig[1u].wdType))

/* cy_capsense_electrodeConfig */
#define CY_CAPSENSE_BUTTON0_RX0_CFG_PTR_VALUE                                    (cy_capsense_context.ptrWdConfig[0].ptrEltdConfig[0].ptrPin)
#define CY_CAPSENSE_BUTTON0_RX0_CFG_PTR_SIZE                                     (sizeof(cy_capsense_context.ptrWdConfig[0].ptrEltdConfig[0].ptrPin))
#define CY_CAPSENSE_BUTTON0_RX0_ELTD_TYPE_VALUE                                  (cy_capsense_context.ptrWdConfig[0].ptrEltdConfig[0].type)
#define CY_CAPSENSE_BUTTON0_RX0_ELTD_TYPE_SIZE                                   (sizeof(cy_capsense_context.ptrWdConfig[0].ptrEltdConfig[0].type))
#define CY_CAPSENSE_BUTTON0_RX0_NUM_PINS_VALUE                                   (cy_capsense_context.ptrWdConfig[0].ptrEltdConfig[0].numPins)
#define CY_CAPSENSE_BUTTON0_RX0_NUM_PINS_SIZE                                    (sizeof(cy_capsense_context.ptrWdConfig[0].ptrEltdConfig[0].numPins))

#define CY_CAPSENSE_BUTTON0_TX_CFG_PTR_VALUE                                     (cy_capsense_context.ptrWdConfig[0].ptrEltdConfig[1].ptrPin)
#define CY_CAPSENSE_BUTTON0_TX_CFG_PTR_SIZE                                      (sizeof(cy_capsense_context.ptrWdConfig[0].ptrEltdConfig[1].ptrPin))
#define CY_CAPSENSE_BUTTON0_TX_ELTD_TYPE_VALUE                                   (cy_capsense_context.ptrWdConfig[0].ptrEltdConfig[1].type)
#define CY_CAPSENSE_BUTTON0_TX_ELTD_TYPE_SIZE                                    (sizeof(cy_capsense_context.ptrWdConfig[0].ptrEltdConfig[1].type))
#define CY_CAPSENSE_BUTTON0_TX_NUM_PINS_VALUE                                    (cy_capsense_context.ptrWdConfig[0].ptrEltdConfig[1].numPins)
#define CY_CAPSENSE_BUTTON0_TX_NUM_PINS_SIZE                                     (sizeof(cy_capsense_context.ptrWdConfig[0].ptrEltdConfig[1].numPins))

#define CY_CAPSENSE_BUTTON1_RX0_CFG_PTR_VALUE                                    (cy_capsense_context.ptrWdConfig[1].ptrEltdConfig[0].ptrPin)
#define CY_CAPSENSE_BUTTON1_RX0_CFG_PTR_SIZE                                     (sizeof(cy_capsense_context.ptrWdConfig[1].ptrEltdConfig[0].ptrPin))
#define CY_CAPSENSE_BUTTON1_RX0_ELTD_TYPE_VALUE                                  (cy_capsense_context.ptrWdConfig[1].ptrEltdConfig[0].type)
#define CY_CAPSENSE_BUTTON1_RX0_ELTD_TYPE_SIZE                                   (sizeof(cy_capsense_context.ptrWdConfig[1].ptrEltdConfig[0].type))
#define CY_CAPSENSE_BUTTON1_RX0_NUM_PINS_VALUE                                   (cy_capsense_context.ptrWdConfig[1].ptrEltdConfig[0].numPins)
#define CY_CAPSENSE_BUTTON1_RX0_NUM_PINS_SIZE                                    (sizeof(cy_capsense_context.ptrWdConfig[1].ptrEltdConfig[0].numPins))

#define CY_CAPSENSE_BUTTON1_TX_CFG_PTR_VALUE                                     (cy_capsense_context.ptrWdConfig[1].ptrEltdConfig[1].ptrPin)
#define CY_CAPSENSE_BUTTON1_TX_CFG_PTR_SIZE                                      (sizeof(cy_capsense_context.ptrWdConfig[1].ptrEltdConfig[1].ptrPin))
#define CY_CAPSENSE_BUTTON1_TX_ELTD_TYPE_VALUE                                   (cy_capsense_context.ptrWdConfig[1].ptrEltdConfig[1].type)
#define CY_CAPSENSE_BUTTON1_TX_ELTD_TYPE_SIZE                                    (sizeof(cy_capsense_context.ptrWdConfig[1].ptrEltdConfig[1].type))
#define CY_CAPSENSE_BUTTON1_TX_NUM_PINS_VALUE                                    (cy_capsense_context.ptrWdConfig[1].ptrEltdConfig[1].numPins)
#define CY_CAPSENSE_BUTTON1_TX_NUM_PINS_SIZE                                     (sizeof(cy_capsense_context.ptrWdConfig[1].ptrEltdConfig[1].numPins))


#if ((CY_CAPSENSE_PERI_CLK / 2) > 48000000)
    #warning The maximum Modulator clock frequency is 48 MHz: increase Modulator clock divider to meet the valid operation conditions
#endif

#if ((CY_CAPSENSE_PERI_CLK / 2 / 13) > 6000000)
    #warning The maximum Tx clock frequency is 6 MHz: increase Tx clock divider for widget Button0 to meet the valid operation conditions
#endif

#if ((CY_CAPSENSE_PERI_CLK / 2 / 15) > 6000000)
    #warning The maximum Tx clock frequency is 6 MHz: increase Tx clock divider for widget Button1 to meet the valid operation conditions
#endif



#if (CY_CAPSENSE_BIST_SUPPORTED)
#if (CY_CAPSENSE_BIST_EN != 0)
extern uint32_t eltdCap[];

extern uint16_t bslnInv[];
#endif
#endif

#if defined(__cplusplus)
}
#endif

#endif /* CY_CAPSENSE_CORE == __CORTEX_M */

#endif /* !defined(CY_DISABLE_CAPSENSE) */

#endif /* CYCFG_CAPSENSE_H */

/* [] END OF FILE */

