/*******************************************************************************
* File Name: cycfg_capsense.c
*
* Description:
* CapSense Middleware configuration
* This file should not be modified. It was automatically generated by
* CapSense Configurator 4.0.0.6066
*
********************************************************************************
* Copyright 2021, Cypress Semiconductor Corporation (an Infineon company) 
* or an affiliate of Cypress Semiconductor Corporation.
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#include "cycfg_capsense.h"

#if !defined(CY_DISABLE_CAPSENSE)

#if (CY_CAPSENSE_CORE == __CORTEX_M)

#ifndef CSD_CMODPADS_PORT
#define CSD_CMODPADS_PORT 0xFF
#endif
#ifndef CSD_CMODPADS_PIN
#define CSD_CMODPADS_PIN 0xFF
#endif
#ifndef CSD_CSH_TANKPADS_PORT
#define CSD_CSH_TANKPADS_PORT 0xFF
#endif
#ifndef CSD_CSH_TANKPADS_PIN
#define CSD_CSH_TANKPADS_PIN 0xFF
#endif
#ifndef CSD_CSHIELDPADS_PORT
#define CSD_CSHIELDPADS_PORT 0xFF
#endif
#ifndef CSD_CSHIELDPADS_PIN
#define CSD_CSHIELDPADS_PIN 0xFF
#endif
#ifndef CSD_VREF_EXT_PORT
#define CSD_VREF_EXT_PORT 0xFF
#endif
#ifndef CSD_VREF_EXT_PIN
#define CSD_VREF_EXT_PIN 0xFF
#endif

static cy_stc_capsense_internal_context_t cy_capsense_internalContext;
static cy_stc_active_scan_sns_t cy_capsense_activeScanSns[CY_MSC_ENABLED_CH_NUMBER];

static cy_stc_msc_base_config_t cy_capsense_baseFrame[CY_CAPSENSE_TOTAL_CH_NUMBER];

#if (CY_CAPSENSE_SENSOR_CONNECTION_MODE_LEGACY == 0)
    static uint32_t cy_capsense_sensorFrameContext[CY_CAPSENSE_SENSOR_FRAME_SIZE * CY_CAPSENSE_SLOT_COUNT * CY_CAPSENSE_TOTAL_CH_NUMBER];
#endif

#if (CY_CAPSENSE_DEBOUNCE_SIZE > 0)
    static uint8_t cy_capsense_debounce[CY_CAPSENSE_DEBOUNCE_SIZE] = {0};
#endif

#if (CY_CAPSENSE_NOISE_ENVELOPE_SIZE > 0)
    static cy_stc_capsense_smartsense_csd_noise_envelope_t cy_capsense_noiseEnvelope[CY_CAPSENSE_NOISE_ENVELOPE_SIZE];
#endif

#if (CY_CAPSENSE_RAW_HISTORY_SIZE > 0)
    static uint16_t cy_capsense_rawFilterHistory[CY_CAPSENSE_RAW_HISTORY_SIZE] = {0};
#endif

#if (CY_CAPSENSE_IIR_HISTORY_LOW_SIZE > 0)
    static uint8_t cy_capsense_iirHistoryLow[CY_CAPSENSE_IIR_HISTORY_LOW_SIZE] = {0};
#endif

#if (CY_CAPSENSE_POSITION_FILTER_HISTORY_SIZE > 0)
    static cy_stc_capsense_position_t cy_capsense_positionFilterHistory[CY_CAPSENSE_POSITION_FILTER_HISTORY_SIZE];
#endif

#if (CY_CAPSENSE_TOUCH_FILTER_HISTORY_SIZE > 0)
    static cy_stc_capsense_touch_t cy_capsense_touchFilterHistory[CY_CAPSENSE_TOUCH_FILTER_HISTORY_SIZE] =
    {
    };
#endif

#if (CY_CAPSENSE_DIPLEX_SIZE > 0)
    static const uint8_t cy_capsense_diplexTable[CY_CAPSENSE_DIPLEX_SIZE] =
    {
    };
#endif

#if (CY_CAPSENSE_CSD_TOUCHPAD_MAX_SENSORS_SIZE > 0)
    static uint16_t cy_capsense_csdTouchBuffer[CY_CAPSENSE_CSD_TOUCHPAD_MAX_SENSORS_SIZE] = {0};
#endif

#if (CY_CAPSENSE_CSX_TOUCH_BUFFER_ENABLE > 0)
    static cy_stc_capsense_csx_touch_buffer_t cy_capsense_csxTouchBuffer;
#endif

#if (CY_CAPSENSE_CSX_TOUCH_HISTORY_SIZE > 0)
    static cy_stc_capsense_csx_touch_history_t cy_capsense_csxTouchHistory[CY_CAPSENSE_CSX_TOUCH_HISTORY_SIZE] =
    {
    };
#endif

#if (CY_CAPSENSE_BALLISTIC_WIDGET_COUNT > 0)
    static cy_stc_capsense_ballistic_context_t cy_capsense_ballisticContext[CY_CAPSENSE_BALLISTIC_WIDGET_COUNT];
#endif

#if (CY_CAPSENSE_GESTURE_WIDGET_COUNT > 0)
    static cy_stc_capsense_gesture_context_t cy_capsense_gestureContext[CY_CAPSENSE_GESTURE_WIDGET_COUNT];
#endif

#if (CY_CAPSENSE_BIST_EN != 0)
    uint16_t cy_capsense_bslnInv[CY_CAPSENSE_SENSOR_COUNT];
    uint32_t cy_capsense_eltdCap[CY_CAPSENSE_ELTD_COUNT];
    uint32_t cy_capsense_snsCap[CY_CAPSENSE_SENSOR_COUNT];
    uint32_t cy_capsense_shieldCap[CY_CAPSENSE_TOTAL_CH_NUMBER];
    uint16_t cy_capsense_wdgtCrc[CY_CAPSENSE_WIDGET_COUNT];
#endif

static cy_stc_msc_channel_config_t cy_capsense_msc_ch_config[CY_MSC_ENABLED_CH_NUMBER] =
{
    {   /* MSC channel 0 */
        .ptrMscBase = CY_MSC0_HW,
        .ptrMscContext = &cy_msc_0_context,
        .portCmod1 = CY_MSC0_Cmod1_PORT,
        .pinCmod1 = CY_MSC0_Cmod1_PIN,
        .portCmod2 = CY_MSC0_Cmod2_PORT,
        .pinCmod2 = CY_MSC0_Cmod2_PIN,
        .dmaWrChIndex = CY_MSC0_WR_DMA_CH_INDEX,
        .dmaChainWrChIndex = CY_MSC0_CHAIN_WR_DMA_CH_INDEX,
        .dmaRdChIndex = CY_MSC0_RD_DMA_CH_INDEX,
        .dmaChainRdChIndex = CY_MSC0_CHAIN_RD_DMA_CH_INDEX,
    },
    {   /* MSC channel 1 */
        .ptrMscBase = CY_MSC1_HW,
        .ptrMscContext = &cy_msc_1_context,
        .portCmod1 = CY_MSC1_Cmod1_PORT,
        .pinCmod1 = CY_MSC1_Cmod1_PIN,
        .portCmod2 = CY_MSC1_Cmod2_PORT,
        .pinCmod2 = CY_MSC1_Cmod2_PIN,
        .dmaWrChIndex = CY_MSC1_WR_DMA_CH_INDEX,
        .dmaChainWrChIndex = CY_MSC1_CHAIN_WR_DMA_CH_INDEX,
        .dmaRdChIndex = CY_MSC1_RD_DMA_CH_INDEX,
        .dmaChainRdChIndex = CY_MSC1_CHAIN_RD_DMA_CH_INDEX,
    },
};

static cy_stc_capsense_scan_slot_t cy_capsense_scanSlots[CY_CAPSENSE_SLOT_COUNT * CY_CAPSENSE_TOTAL_CH_NUMBER] =
{
    /* Channel MSC0 */
    {   /* Slot 0 */
        CY_CAPSENSE_BUTTON0_WDGT_ID,
        CY_CAPSENSE_BUTTON0_SNS0_ID
    },
    {   /* Slot 1 */
        CY_CAPSENSE_TOUCHPAD0_WDGT_ID,
        CY_CAPSENSE_TOUCHPAD0_SNS8_ID
    },
    {   /* Slot 2 */
        CY_CAPSENSE_TOUCHPAD0_WDGT_ID,
        CY_CAPSENSE_TOUCHPAD0_SNS9_ID
    },
    {   /* Slot 3 */
        CY_CAPSENSE_TOUCHPAD0_WDGT_ID,
        CY_CAPSENSE_TOUCHPAD0_SNS10_ID
    },
    {   /* Slot 4 */
        CY_CAPSENSE_TOUCHPAD0_WDGT_ID,
        CY_CAPSENSE_TOUCHPAD0_SNS11_ID
    },
    {   /* Slot 5 */
        CY_CAPSENSE_TOUCHPAD0_WDGT_ID,
        CY_CAPSENSE_TOUCHPAD0_SNS12_ID
    },
    {   /* Slot 6 */
        CY_CAPSENSE_TOUCHPAD0_WDGT_ID,
        CY_CAPSENSE_TOUCHPAD0_SNS13_ID
    },
    {   /* Slot 7 */
        CY_CAPSENSE_TOUCHPAD0_WDGT_ID,
        CY_CAPSENSE_TOUCHPAD0_SNS14_ID
    },
    {   /* Slot 8 */
        CY_CAPSENSE_TOUCHPAD0_WDGT_ID,
        CY_CAPSENSE_TOUCHPAD0_SNS15_ID
    },
    {   /* Slot 9 */
        CY_CAPSENSE_TOUCHPAD0_WDGT_ID,
        CY_CAPSENSE_TOUCHPAD0_SNS21_ID
    },
    {   /* Slot 10 */
        CY_CAPSENSE_TOUCHPAD0_WDGT_ID,
        CY_CAPSENSE_TOUCHPAD0_SNS22_ID
    },
    {   /* Slot 11 */
        CY_CAPSENSE_TOUCHPAD0_WDGT_ID,
        CY_CAPSENSE_TOUCHPAD0_SNS23_ID
    },
    {   /* Slot 12 */
        CY_CAPSENSE_TOUCHPAD0_WDGT_ID,
        CY_CAPSENSE_TOUCHPAD0_SNS24_ID
    },
    {   /* Slot 13 */
        CY_CAPSENSE_TOUCHPAD0_WDGT_ID,
        CY_CAPSENSE_TOUCHPAD0_SNS25_ID
    },
    {   /* Slot 14 */
        CY_CAPSENSE_LINEARSLIDER0_WDGT_ID,
        CY_CAPSENSE_LINEARSLIDER0_SNS0_ID
    },
    {   /* Slot 15 */
        CY_CAPSENSE_LINEARSLIDER0_WDGT_ID,
        CY_CAPSENSE_LINEARSLIDER0_SNS1_ID
    },
    {   /* Slot 16 */
        CY_CAPSENSE_LINEARSLIDER0_WDGT_ID,
        CY_CAPSENSE_LINEARSLIDER0_SNS2_ID
    },
    {   /* Slot 17 */
        CY_CAPSENSE_LINEARSLIDER0_WDGT_ID,
        CY_CAPSENSE_LINEARSLIDER0_SNS3_ID
    },
    {   /* Slot 18 */
        CY_CAPSENSE_LINEARSLIDER0_WDGT_ID,
        CY_CAPSENSE_LINEARSLIDER0_SNS4_ID
    },
    {   /* Slot 19 */
        CY_CAPSENSE_LINEARSLIDER0_WDGT_ID,
        CY_CAPSENSE_LINEARSLIDER0_SNS5_ID
    },
    {   /* Slot 20 */
        CY_CAPSENSE_LINEARSLIDER0_WDGT_ID,
        CY_CAPSENSE_LINEARSLIDER0_SNS6_ID
    },
    {   /* Slot 21 */
        CY_CAPSENSE_LINEARSLIDER0_WDGT_ID,
        CY_CAPSENSE_LINEARSLIDER0_SNS7_ID
    },
    /* Channel MSC1 */
    {   /* Slot 0 */
        CY_CAPSENSE_BUTTON1_WDGT_ID,
        CY_CAPSENSE_BUTTON1_SNS0_ID
    },
    {   /* Slot 1 */
        CY_CAPSENSE_TOUCHPAD0_WDGT_ID,
        CY_CAPSENSE_TOUCHPAD0_SNS0_ID
    },
    {   /* Slot 2 */
        CY_CAPSENSE_TOUCHPAD0_WDGT_ID,
        CY_CAPSENSE_TOUCHPAD0_SNS1_ID
    },
    {   /* Slot 3 */
        CY_CAPSENSE_TOUCHPAD0_WDGT_ID,
        CY_CAPSENSE_TOUCHPAD0_SNS2_ID
    },
    {   /* Slot 4 */
        CY_CAPSENSE_TOUCHPAD0_WDGT_ID,
        CY_CAPSENSE_TOUCHPAD0_SNS3_ID
    },
    {   /* Slot 5 */
        CY_CAPSENSE_TOUCHPAD0_WDGT_ID,
        CY_CAPSENSE_TOUCHPAD0_SNS4_ID
    },
    {   /* Slot 6 */
        CY_CAPSENSE_TOUCHPAD0_WDGT_ID,
        CY_CAPSENSE_TOUCHPAD0_SNS5_ID
    },
    {   /* Slot 7 */
        CY_CAPSENSE_TOUCHPAD0_WDGT_ID,
        CY_CAPSENSE_TOUCHPAD0_SNS6_ID
    },
    {   /* Slot 8 */
        CY_CAPSENSE_TOUCHPAD0_WDGT_ID,
        CY_CAPSENSE_TOUCHPAD0_SNS7_ID
    },
    {   /* Slot 9 */
        CY_CAPSENSE_TOUCHPAD0_WDGT_ID,
        CY_CAPSENSE_TOUCHPAD0_SNS16_ID
    },
    {   /* Slot 10 */
        CY_CAPSENSE_TOUCHPAD0_WDGT_ID,
        CY_CAPSENSE_TOUCHPAD0_SNS17_ID
    },
    {   /* Slot 11 */
        CY_CAPSENSE_TOUCHPAD0_WDGT_ID,
        CY_CAPSENSE_TOUCHPAD0_SNS18_ID
    },
    {   /* Slot 12 */
        CY_CAPSENSE_TOUCHPAD0_WDGT_ID,
        CY_CAPSENSE_TOUCHPAD0_SNS19_ID
    },
    {   /* Slot 13 */
        CY_CAPSENSE_TOUCHPAD0_WDGT_ID,
        CY_CAPSENSE_TOUCHPAD0_SNS20_ID
    },
    {   /* Slot 14 */
        0xFFFDu,
        0u
    },
    {   /* Slot 15 */
        0xFFFDu,
        0u
    },
    {   /* Slot 16 */
        0xFFFDu,
        0u
    },
    {   /* Slot 17 */
        0xFFFDu,
        0u
    },
    {   /* Slot 18 */
        0xFFFDu,
        0u
    },
    {   /* Slot 19 */
        0xFFFDu,
        0u
    },
    {   /* Slot 20 */
        0xFFFDu,
        0u
    },
    {   /* Slot 21 */
        0xFFFDu,
        0u
    },
};

#if ((CY_CAPSENSE_DMA_CONFIGURED != 0) && (CY_CAPSENSE_SENSOR_CONNECTION_MODE_LEGACY == 0))
static const uint32_t *ptrDmaWrChSnsConfigs[CY_CAPSENSE_SLOT_COUNT * CY_CAPSENSE_TOTAL_CH_NUMBER] = {
    &cy_capsense_sensorFrameContext[0u],
    &cy_capsense_sensorFrameContext[6u],
    &cy_capsense_sensorFrameContext[12u],
    &cy_capsense_sensorFrameContext[18u],
    &cy_capsense_sensorFrameContext[24u],
    &cy_capsense_sensorFrameContext[30u],
    &cy_capsense_sensorFrameContext[36u],
    &cy_capsense_sensorFrameContext[42u],
    &cy_capsense_sensorFrameContext[48u],
    &cy_capsense_sensorFrameContext[54u],
    &cy_capsense_sensorFrameContext[60u],
    &cy_capsense_sensorFrameContext[66u],
    &cy_capsense_sensorFrameContext[72u],
    &cy_capsense_sensorFrameContext[78u],
    &cy_capsense_sensorFrameContext[84u],
    &cy_capsense_sensorFrameContext[90u],
    &cy_capsense_sensorFrameContext[96u],
    &cy_capsense_sensorFrameContext[102u],
    &cy_capsense_sensorFrameContext[108u],
    &cy_capsense_sensorFrameContext[114u],
    &cy_capsense_sensorFrameContext[120u],
    &cy_capsense_sensorFrameContext[126u],
    &cy_capsense_sensorFrameContext[132u],
    &cy_capsense_sensorFrameContext[138u],
    &cy_capsense_sensorFrameContext[144u],
    &cy_capsense_sensorFrameContext[150u],
    &cy_capsense_sensorFrameContext[156u],
    &cy_capsense_sensorFrameContext[162u],
    &cy_capsense_sensorFrameContext[168u],
    &cy_capsense_sensorFrameContext[174u],
    &cy_capsense_sensorFrameContext[180u],
    &cy_capsense_sensorFrameContext[186u],
    &cy_capsense_sensorFrameContext[192u],
    &cy_capsense_sensorFrameContext[198u],
    &cy_capsense_sensorFrameContext[204u],
    &cy_capsense_sensorFrameContext[210u],
    &cy_capsense_sensorFrameContext[216u],
    &cy_capsense_sensorFrameContext[222u],
    &cy_capsense_sensorFrameContext[228u],
    &cy_capsense_sensorFrameContext[234u],
    &cy_capsense_sensorFrameContext[240u],
    &cy_capsense_sensorFrameContext[246u],
    &cy_capsense_sensorFrameContext[252u],
    &cy_capsense_sensorFrameContext[258u],
};

static uint16_t emptySlotValue = 0u;
static const uint16_t *ptrDmaRdChSnsConfigs[CY_CAPSENSE_SLOT_COUNT * CY_CAPSENSE_TOTAL_CH_NUMBER] = {
    &cy_capsense_tuner.sensorContext[0u].raw,
    &cy_capsense_tuner.sensorContext[10u].raw,
    &cy_capsense_tuner.sensorContext[11u].raw,
    &cy_capsense_tuner.sensorContext[12u].raw,
    &cy_capsense_tuner.sensorContext[13u].raw,
    &cy_capsense_tuner.sensorContext[14u].raw,
    &cy_capsense_tuner.sensorContext[15u].raw,
    &cy_capsense_tuner.sensorContext[16u].raw,
    &cy_capsense_tuner.sensorContext[17u].raw,
    &cy_capsense_tuner.sensorContext[23u].raw,
    &cy_capsense_tuner.sensorContext[24u].raw,
    &cy_capsense_tuner.sensorContext[25u].raw,
    &cy_capsense_tuner.sensorContext[26u].raw,
    &cy_capsense_tuner.sensorContext[27u].raw,
    &cy_capsense_tuner.sensorContext[28u].raw,
    &cy_capsense_tuner.sensorContext[29u].raw,
    &cy_capsense_tuner.sensorContext[30u].raw,
    &cy_capsense_tuner.sensorContext[31u].raw,
    &cy_capsense_tuner.sensorContext[32u].raw,
    &cy_capsense_tuner.sensorContext[33u].raw,
    &cy_capsense_tuner.sensorContext[34u].raw,
    &cy_capsense_tuner.sensorContext[35u].raw,
    &cy_capsense_tuner.sensorContext[1u].raw,
    &cy_capsense_tuner.sensorContext[2u].raw,
    &cy_capsense_tuner.sensorContext[3u].raw,
    &cy_capsense_tuner.sensorContext[4u].raw,
    &cy_capsense_tuner.sensorContext[5u].raw,
    &cy_capsense_tuner.sensorContext[6u].raw,
    &cy_capsense_tuner.sensorContext[7u].raw,
    &cy_capsense_tuner.sensorContext[8u].raw,
    &cy_capsense_tuner.sensorContext[9u].raw,
    &cy_capsense_tuner.sensorContext[18u].raw,
    &cy_capsense_tuner.sensorContext[19u].raw,
    &cy_capsense_tuner.sensorContext[20u].raw,
    &cy_capsense_tuner.sensorContext[21u].raw,
    &cy_capsense_tuner.sensorContext[22u].raw,
    &emptySlotValue,
    &emptySlotValue,
    &emptySlotValue,
    &emptySlotValue,
    &emptySlotValue,
    &emptySlotValue,
    &emptySlotValue,
    &emptySlotValue,
};
#endif

static const cy_stc_capsense_common_config_t cy_capsense_commonConfig =
{
    .cpuClkHz = CY_CAPSENSE_CPU_CLK,
    .periClkHz = CY_CAPSENSE_PERI_CLK,
    .vdda = CY_CAPSENSE_VDDA_MV,
    .numPin = CY_CAPSENSE_PIN_COUNT,
    .numSns = CY_CAPSENSE_SENSOR_COUNT,
    .numWd = CY_CAPSENSE_WIDGET_COUNT,
    .csdEn = CY_CAPSENSE_ENABLE,
    .csxEn = CY_CAPSENSE_DISABLE,
    .bistEn = CY_CAPSENSE_DISABLE,
    .positionFilterEn = CY_CAPSENSE_DISABLE,
    .periDividerType = (uint8_t)CY_CAPSENSE_PERI_DIV_TYPE,
    .periDividerIndex = CY_CAPSENSE_PERI_DIV_INDEX,
    .analogWakeupDelay = 10u,
    .proxTouchCoeff = 300u,
    .swSensorAutoResetEn = CY_CAPSENSE_DISABLE,
    .csdInactiveSnsConnection = CY_CAPSENSE_SNS_CONNECTION_SHIELD,
    .csxInactiveSnsConnection = CY_CAPSENSE_SNS_CONNECTION_GROUND,
    .csdRConst = 1000u,
    .csdShieldNumPin = 2u,
    .csdRawTarget = 85u,
    .csdAutotuneEn = CY_CAPSENSE_CSD_SS_DIS,
    .csdCalibrationError = 10u,
    .csxRawTarget = 40u,
    .csxCalibrationError = 20u,
    .ptrMscChConfig = &cy_capsense_msc_ch_config[0u],
#if ((CY_CAPSENSE_DMA_CONFIGURED != 0) && (CY_CAPSENSE_SENSOR_CONNECTION_MODE_LEGACY == 0))
    .ptrDmacBase = DMAC,
    .ptrDmaWrChSnsCfgAddr = ptrDmaWrChSnsConfigs,
    .ptrDmaRdChSnsCfgAddr = ptrDmaRdChSnsConfigs,
#endif
    .csdShieldMode = CY_CAPSENSE_SHIELD_ACTIVE,
    .sensorConnection = CY_CAPSENSE_CTRLMUX_SENSOR_CONNECTION_METHOD,
    .csdCdacAutocalEn = CY_CAPSENSE_ENABLE,
    .csdRefCdacAutoEn = CY_CAPSENSE_ENABLE,
    .csdCdacCompEn = CY_CAPSENSE_ENABLE,
    .csdCdacCompDivAutoEn = CY_CAPSENSE_ENABLE,
    .csdCdacAutoCalibMin = 6u,
    .csdRefCdacRowColumnAlignEn = CY_CAPSENSE_ENABLE,
    .csxCdacAutocalEn = CY_CAPSENSE_DISABLE,
    .csxRefCdacAutoEn = CY_CAPSENSE_DISABLE,
    .csxCdacCompEn = CY_CAPSENSE_DISABLE,
    .csxCdacCompDivAutoEn = CY_CAPSENSE_DISABLE,
    .csxCdacAutoCalibMin = 6u,
    .csxAutotuneEn = CY_CAPSENSE_CSD_SS_DIS,
    .numProOffsetCycles = 0u,
    .proOffsetCdacComp = 0u,
    .scanningMode = CY_CAPSENSE_SCAN_MODE_DMA_DRIVEN,
    .mptxEn = CY_CAPSENSE_DISABLE,
    .numEpiCycles = 20u,
    .chopPolarity = CY_CAPSENSE_DISABLE,
    .numCoarseInitChargeCycles = 60u,
    .numCoarseInitSettleCycles = 60u,
    .cicFilterMode = CY_CAPSENSE_CIC_FILTER,
    .numBadScans = 0u,
    .counterMode = CY_CAPSENSE_COUNTER_MODE_SATURATE,
    .syncFrameStartEn = CY_CAPSENSE_DISABLE,
    .syncClockEn = CY_CAPSENSE_DISABLE,
    .syncMode = CY_CAPSENSE_SYNC_INTERNAL,
    .masterChannelId = 0u,
    .numChips = 1u,
    .numChannels = CY_MSC_ENABLED_CH_NUMBER,
    .numSlots = CY_CAPSENSE_SLOT_COUNT,
    .channelOffset = CY_MSC_CHANNEL_OFFSET,
};

#if (CY_CAPSENSE_MULTI_PHASE_ENABLED)
    static cy_stc_capsense_mptx_table_t cy_capsense_mptx_table[CY_CAPSENSE_MPTX_WIDGET_NUMBER] =
    {
    };
#endif

static const cy_stc_capsense_pin_config_t cy_capsense_pinConfig[CY_CAPSENSE_PIN_COUNT] =
{
    { /* Button0_Sns0 */
        Button0_Sns0_PORT,
        Button0_Sns0_PIN,
        Button0_Sns0_PAD,
        0u,
    },
    { /* Button1_Sns0 */
        Button1_Sns0_PORT,
        Button1_Sns0_PIN,
        Button1_Sns0_PAD,
        1u,
    },
    { /* Touchpad0_Col0 */
        Touchpad0_Col0_PORT,
        Touchpad0_Col0_PIN,
        Touchpad0_Col0_PAD,
        1u,
    },
    { /* Touchpad0_Col1 */
        Touchpad0_Col1_PORT,
        Touchpad0_Col1_PIN,
        Touchpad0_Col1_PAD,
        1u,
    },
    { /* Touchpad0_Col2 */
        Touchpad0_Col2_PORT,
        Touchpad0_Col2_PIN,
        Touchpad0_Col2_PAD,
        1u,
    },
    { /* Touchpad0_Col3 */
        Touchpad0_Col3_PORT,
        Touchpad0_Col3_PIN,
        Touchpad0_Col3_PAD,
        1u,
    },
    { /* Touchpad0_Col4 */
        Touchpad0_Col4_PORT,
        Touchpad0_Col4_PIN,
        Touchpad0_Col4_PAD,
        1u,
    },
    { /* Touchpad0_Col5 */
        Touchpad0_Col5_PORT,
        Touchpad0_Col5_PIN,
        Touchpad0_Col5_PAD,
        1u,
    },
    { /* Touchpad0_Col6 */
        Touchpad0_Col6_PORT,
        Touchpad0_Col6_PIN,
        Touchpad0_Col6_PAD,
        1u,
    },
    { /* Touchpad0_Col7 */
        Touchpad0_Col7_PORT,
        Touchpad0_Col7_PIN,
        Touchpad0_Col7_PAD,
        1u,
    },
    { /* Touchpad0_Col8 */
        Touchpad0_Col8_PORT,
        Touchpad0_Col8_PIN,
        Touchpad0_Col8_PAD,
        0u,
    },
    { /* Touchpad0_Col9 */
        Touchpad0_Col9_PORT,
        Touchpad0_Col9_PIN,
        Touchpad0_Col9_PAD,
        0u,
    },
    { /* Touchpad0_Col10 */
        Touchpad0_Col10_PORT,
        Touchpad0_Col10_PIN,
        Touchpad0_Col10_PAD,
        0u,
    },
    { /* Touchpad0_Col11 */
        Touchpad0_Col11_PORT,
        Touchpad0_Col11_PIN,
        Touchpad0_Col11_PAD,
        0u,
    },
    { /* Touchpad0_Col12 */
        Touchpad0_Col12_PORT,
        Touchpad0_Col12_PIN,
        Touchpad0_Col12_PAD,
        0u,
    },
    { /* Touchpad0_Col13 */
        Touchpad0_Col13_PORT,
        Touchpad0_Col13_PIN,
        Touchpad0_Col13_PAD,
        0u,
    },
    { /* Touchpad0_Col14 */
        Touchpad0_Col14_PORT,
        Touchpad0_Col14_PIN,
        Touchpad0_Col14_PAD,
        0u,
    },
    { /* Touchpad0_Col15 */
        Touchpad0_Col15_PORT,
        Touchpad0_Col15_PIN,
        Touchpad0_Col15_PAD,
        0u,
    },
    { /* Touchpad0_Row0 */
        Touchpad0_Row0_PORT,
        Touchpad0_Row0_PIN,
        Touchpad0_Row0_PAD,
        1u,
    },
    { /* Touchpad0_Row1 */
        Touchpad0_Row1_PORT,
        Touchpad0_Row1_PIN,
        Touchpad0_Row1_PAD,
        1u,
    },
    { /* Touchpad0_Row2 */
        Touchpad0_Row2_PORT,
        Touchpad0_Row2_PIN,
        Touchpad0_Row2_PAD,
        1u,
    },
    { /* Touchpad0_Row3 */
        Touchpad0_Row3_PORT,
        Touchpad0_Row3_PIN,
        Touchpad0_Row3_PAD,
        1u,
    },
    { /* Touchpad0_Row4 */
        Touchpad0_Row4_PORT,
        Touchpad0_Row4_PIN,
        Touchpad0_Row4_PAD,
        1u,
    },
    { /* Touchpad0_Row5 */
        Touchpad0_Row5_PORT,
        Touchpad0_Row5_PIN,
        Touchpad0_Row5_PAD,
        0u,
    },
    { /* Touchpad0_Row6 */
        Touchpad0_Row6_PORT,
        Touchpad0_Row6_PIN,
        Touchpad0_Row6_PAD,
        0u,
    },
    { /* Touchpad0_Row7 */
        Touchpad0_Row7_PORT,
        Touchpad0_Row7_PIN,
        Touchpad0_Row7_PAD,
        0u,
    },
    { /* Touchpad0_Row8 */
        Touchpad0_Row8_PORT,
        Touchpad0_Row8_PIN,
        Touchpad0_Row8_PAD,
        0u,
    },
    { /* Touchpad0_Row9 */
        Touchpad0_Row9_PORT,
        Touchpad0_Row9_PIN,
        Touchpad0_Row9_PAD,
        0u,
    },
};

#if (CY_CAPSENSE_SHIELD_PIN_COUNT > 0)
    static const cy_stc_capsense_pin_config_t cy_capsense_shieldPinConfig[CY_CAPSENSE_SHIELD_PIN_COUNT] =
    {
    { /* Shield0 */
        Shield0_PORT,
        Shield0_PIN,
        Shield0_PAD,
        0u,
    },
    { /* Shield1 */
        Shield1_PORT,
        Shield1_PIN,
        Shield1_PAD,
        1u,
    },
    };
#endif

#if (CY_CAPSENSE_ELTD_COUNT > 0)
    static const cy_stc_capsense_electrode_config_t cy_capsense_electrodeConfig[CY_CAPSENSE_ELTD_COUNT] =
    {
        { /* Button0_Sns0 */
            .ptrPin = &cy_capsense_pinConfig[0u],
            .type = 0u,
            .numPins = 1u,
            .chId = 0u,
        },
        { /* Button1_Sns0 */
            .ptrPin = &cy_capsense_pinConfig[1u],
            .type = 0u,
            .numPins = 1u,
            .chId = 1u,
        },
        { /* Touchpad0_Col0 */
            .ptrPin = &cy_capsense_pinConfig[2u],
            .type = 0u,
            .numPins = 1u,
            .chId = 1u,
        },
        { /* Touchpad0_Col1 */
            .ptrPin = &cy_capsense_pinConfig[3u],
            .type = 0u,
            .numPins = 1u,
            .chId = 1u,
        },
        { /* Touchpad0_Col2 */
            .ptrPin = &cy_capsense_pinConfig[4u],
            .type = 0u,
            .numPins = 1u,
            .chId = 1u,
        },
        { /* Touchpad0_Col3 */
            .ptrPin = &cy_capsense_pinConfig[5u],
            .type = 0u,
            .numPins = 1u,
            .chId = 1u,
        },
        { /* Touchpad0_Col4 */
            .ptrPin = &cy_capsense_pinConfig[6u],
            .type = 0u,
            .numPins = 1u,
            .chId = 1u,
        },
        { /* Touchpad0_Col5 */
            .ptrPin = &cy_capsense_pinConfig[7u],
            .type = 0u,
            .numPins = 1u,
            .chId = 1u,
        },
        { /* Touchpad0_Col6 */
            .ptrPin = &cy_capsense_pinConfig[8u],
            .type = 0u,
            .numPins = 1u,
            .chId = 1u,
        },
        { /* Touchpad0_Col7 */
            .ptrPin = &cy_capsense_pinConfig[9u],
            .type = 0u,
            .numPins = 1u,
            .chId = 1u,
        },
        { /* Touchpad0_Col8 */
            .ptrPin = &cy_capsense_pinConfig[10u],
            .type = 0u,
            .numPins = 1u,
            .chId = 0u,
        },
        { /* Touchpad0_Col9 */
            .ptrPin = &cy_capsense_pinConfig[11u],
            .type = 0u,
            .numPins = 1u,
            .chId = 0u,
        },
        { /* Touchpad0_Col10 */
            .ptrPin = &cy_capsense_pinConfig[12u],
            .type = 0u,
            .numPins = 1u,
            .chId = 0u,
        },
        { /* Touchpad0_Col11 */
            .ptrPin = &cy_capsense_pinConfig[13u],
            .type = 0u,
            .numPins = 1u,
            .chId = 0u,
        },
        { /* Touchpad0_Col12 */
            .ptrPin = &cy_capsense_pinConfig[14u],
            .type = 0u,
            .numPins = 1u,
            .chId = 0u,
        },
        { /* Touchpad0_Col13 */
            .ptrPin = &cy_capsense_pinConfig[15u],
            .type = 0u,
            .numPins = 1u,
            .chId = 0u,
        },
        { /* Touchpad0_Col14 */
            .ptrPin = &cy_capsense_pinConfig[16u],
            .type = 0u,
            .numPins = 1u,
            .chId = 0u,
        },
        { /* Touchpad0_Col15 */
            .ptrPin = &cy_capsense_pinConfig[17u],
            .type = 0u,
            .numPins = 1u,
            .chId = 0u,
        },
        { /* Touchpad0_Row0 */
            .ptrPin = &cy_capsense_pinConfig[18u],
            .type = 0u,
            .numPins = 1u,
            .chId = 1u,
        },
        { /* Touchpad0_Row1 */
            .ptrPin = &cy_capsense_pinConfig[19u],
            .type = 0u,
            .numPins = 1u,
            .chId = 1u,
        },
        { /* Touchpad0_Row2 */
            .ptrPin = &cy_capsense_pinConfig[20u],
            .type = 0u,
            .numPins = 1u,
            .chId = 1u,
        },
        { /* Touchpad0_Row3 */
            .ptrPin = &cy_capsense_pinConfig[21u],
            .type = 0u,
            .numPins = 1u,
            .chId = 1u,
        },
        { /* Touchpad0_Row4 */
            .ptrPin = &cy_capsense_pinConfig[22u],
            .type = 0u,
            .numPins = 1u,
            .chId = 1u,
        },
        { /* Touchpad0_Row5 */
            .ptrPin = &cy_capsense_pinConfig[23u],
            .type = 0u,
            .numPins = 1u,
            .chId = 0u,
        },
        { /* Touchpad0_Row6 */
            .ptrPin = &cy_capsense_pinConfig[24u],
            .type = 0u,
            .numPins = 1u,
            .chId = 0u,
        },
        { /* Touchpad0_Row7 */
            .ptrPin = &cy_capsense_pinConfig[25u],
            .type = 0u,
            .numPins = 1u,
            .chId = 0u,
        },
        { /* Touchpad0_Row8 */
            .ptrPin = &cy_capsense_pinConfig[26u],
            .type = 0u,
            .numPins = 1u,
            .chId = 0u,
        },
        { /* Touchpad0_Row9 */
            .ptrPin = &cy_capsense_pinConfig[27u],
            .type = 0u,
            .numPins = 1u,
            .chId = 0u,
        },
        { /* LinearSlider0_Sns0 */
            .ptrPin = &cy_capsense_pinConfig[23u],
            .type = 0u,
            .numPins = 1u,
            .chId = 0u,
        },
        { /* LinearSlider0_Sns1 */
            .ptrPin = &cy_capsense_pinConfig[24u],
            .type = 0u,
            .numPins = 1u,
            .chId = 0u,
        },
        { /* LinearSlider0_Sns2 */
            .ptrPin = &cy_capsense_pinConfig[25u],
            .type = 0u,
            .numPins = 1u,
            .chId = 0u,
        },
        { /* LinearSlider0_Sns3 */
            .ptrPin = &cy_capsense_pinConfig[26u],
            .type = 0u,
            .numPins = 1u,
            .chId = 0u,
        },
        { /* LinearSlider0_Sns4 */
            .ptrPin = &cy_capsense_pinConfig[27u],
            .type = 0u,
            .numPins = 1u,
            .chId = 0u,
        },
        { /* LinearSlider0_Sns5 */
            .ptrPin = &cy_capsense_pinConfig[15u],
            .type = 0u,
            .numPins = 1u,
            .chId = 0u,
        },
        { /* LinearSlider0_Sns6 */
            .ptrPin = &cy_capsense_pinConfig[14u],
            .type = 0u,
            .numPins = 1u,
            .chId = 0u,
        },
        { /* LinearSlider0_Sns7 */
            .ptrPin = &cy_capsense_pinConfig[13u],
            .type = 0u,
            .numPins = 1u,
            .chId = 0u,
        },
    };
#endif

static const cy_stc_capsense_widget_config_t cy_capsense_widgetConfig[CY_CAPSENSE_WIDGET_COUNT] =
{
    { /* Button0 */
        .ptrWdContext = &cy_capsense_tuner.widgetContext[0u],
        .ptrSnsContext = &cy_capsense_tuner.sensorContext[0u],
        .ptrEltdConfig = &cy_capsense_electrodeConfig[0u],
        .ptrEltdCapacitance = NULL,
        .ptrSnsCapacitance = NULL,
        .ptrBslnInv = NULL,
        .ptrNoiseEnvelope = NULL,
        .ptrRawFilterHistory = NULL,
        .ptrRawFilterHistoryLow = NULL,
        .iirCoeff = 128u,
        .ptrDebounceArr = &cy_capsense_debounce[0u],
        .ptrDiplexTable = NULL,
        .centroidConfig = 0u,
        .xResolution = 0u,
        .yResolution = 0u,
        .numSns = 1u,
        .numCols = 1u,
        .numRows = 0u,
        .ptrPosFilterHistory = NULL,
        .ptrCsxTouchHistory = NULL,
        .ptrCsxTouchBuffer = NULL,
        .ptrCsdTouchBuffer = NULL,
        .ptrGestureConfig = NULL,
        .ptrGestureContext = NULL,
        .ballisticConfig = {
            .accelCoeff = 9u,
            .speedCoeff = 2u,
            .divisorValue = 4u,
            .speedThresholdX = 3u,
            .speedThresholdY = 4u,
        },
        .ptrBallisticContext = NULL,
        .aiirConfig = {
            .maxK = 60u,
            .minK = 1u,
            .noMovTh = 3u,
            .littleMovTh = 7u,
            .largeMovTh = 12u,
            .divVal = 64u,
        },
        .advConfig = {
            .penultimateTh = 100u,
            .virtualSnsTh = 100u,
            .crossCouplingTh = 5u,
        },
        .posFilterConfig = 0u,
        .rawFilterConfig = 0u,
        .senseMethod = CY_CAPSENSE_CSD_GROUP,
        .wdType = (uint8_t)CY_CAPSENSE_WD_BUTTON_E,
        .ptrMptxTable = NULL,
        .firstSlotId = 0u,
        .numSlots = 1u,
        .numChopCycles = 1u,
        .mptxOrder = 1u,
        .lfsrDitherLimit = 10u,
        .snsClkSourceAutoSelMode = CY_CAPSENSE_SNS_CLK_SOURCE_AUTO_SEL_MODE_STRONG,
        .mfsConfig = 0u,
    },
    { /* Button1 */
        .ptrWdContext = &cy_capsense_tuner.widgetContext[1u],
        .ptrSnsContext = &cy_capsense_tuner.sensorContext[1u],
        .ptrEltdConfig = &cy_capsense_electrodeConfig[1u],
        .ptrEltdCapacitance = NULL,
        .ptrSnsCapacitance = NULL,
        .ptrBslnInv = NULL,
        .ptrNoiseEnvelope = NULL,
        .ptrRawFilterHistory = NULL,
        .ptrRawFilterHistoryLow = NULL,
        .iirCoeff = 128u,
        .ptrDebounceArr = &cy_capsense_debounce[1u],
        .ptrDiplexTable = NULL,
        .centroidConfig = 0u,
        .xResolution = 0u,
        .yResolution = 0u,
        .numSns = 1u,
        .numCols = 1u,
        .numRows = 0u,
        .ptrPosFilterHistory = NULL,
        .ptrCsxTouchHistory = NULL,
        .ptrCsxTouchBuffer = NULL,
        .ptrCsdTouchBuffer = NULL,
        .ptrGestureConfig = NULL,
        .ptrGestureContext = NULL,
        .ballisticConfig = {
            .accelCoeff = 9u,
            .speedCoeff = 2u,
            .divisorValue = 4u,
            .speedThresholdX = 3u,
            .speedThresholdY = 4u,
        },
        .ptrBallisticContext = NULL,
        .aiirConfig = {
            .maxK = 60u,
            .minK = 1u,
            .noMovTh = 3u,
            .littleMovTh = 7u,
            .largeMovTh = 12u,
            .divVal = 64u,
        },
        .advConfig = {
            .penultimateTh = 100u,
            .virtualSnsTh = 100u,
            .crossCouplingTh = 5u,
        },
        .posFilterConfig = 0u,
        .rawFilterConfig = 0u,
        .senseMethod = CY_CAPSENSE_CSD_GROUP,
        .wdType = (uint8_t)CY_CAPSENSE_WD_BUTTON_E,
        .ptrMptxTable = NULL,
        .firstSlotId = 0u,
        .numSlots = 1u,
        .numChopCycles = 1u,
        .mptxOrder = 1u,
        .lfsrDitherLimit = 10u,
        .snsClkSourceAutoSelMode = CY_CAPSENSE_SNS_CLK_SOURCE_AUTO_SEL_MODE_STRONG,
        .mfsConfig = 0u,
    },
    { /* Touchpad0 */
        .ptrWdContext = &cy_capsense_tuner.widgetContext[2u],
        .ptrSnsContext = &cy_capsense_tuner.sensorContext[2u],
        .ptrEltdConfig = &cy_capsense_electrodeConfig[2u],
        .ptrEltdCapacitance = NULL,
        .ptrSnsCapacitance = NULL,
        .ptrBslnInv = NULL,
        .ptrNoiseEnvelope = NULL,
        .ptrRawFilterHistory = NULL,
        .ptrRawFilterHistoryLow = NULL,
        .iirCoeff = 128u,
        .ptrDebounceArr = &cy_capsense_debounce[2u],
        .ptrDiplexTable = NULL,
        .centroidConfig = 161u,
        .xResolution = 160u,
        .yResolution = 100u,
        .numSns = 26u,
        .numCols = 16u,
        .numRows = 10u,
        .ptrPosFilterHistory = NULL,
        .ptrCsxTouchHistory = NULL,
        .ptrCsxTouchBuffer = NULL,
        .ptrCsdTouchBuffer = NULL,
        .ptrGestureConfig = NULL,
        .ptrGestureContext = NULL,
        .ballisticConfig = {
            .accelCoeff = 9u,
            .speedCoeff = 2u,
            .divisorValue = 4u,
            .speedThresholdX = 3u,
            .speedThresholdY = 4u,
        },
        .ptrBallisticContext = NULL,
        .aiirConfig = {
            .maxK = 60u,
            .minK = 1u,
            .noMovTh = 3u,
            .littleMovTh = 7u,
            .largeMovTh = 12u,
            .divVal = 64u,
        },
        .advConfig = {
            .penultimateTh = 100u,
            .virtualSnsTh = 100u,
            .crossCouplingTh = 5u,
        },
        .posFilterConfig = 0u,
        .rawFilterConfig = 0u,
        .senseMethod = CY_CAPSENSE_CSD_GROUP,
        .wdType = (uint8_t)CY_CAPSENSE_WD_TOUCHPAD_E,
        .ptrMptxTable = NULL,
        .firstSlotId = 1u,
        .numSlots = 13u,
        .numChopCycles = 1u,
        .mptxOrder = 1u,
        .lfsrDitherLimit = 10u,
        .snsClkSourceAutoSelMode = CY_CAPSENSE_SNS_CLK_SOURCE_AUTO_SEL_MODE_STRONG,
        .mfsConfig = 0u,
    },
    { /* LinearSlider0 */
        .ptrWdContext = &cy_capsense_tuner.widgetContext[3u],
        .ptrSnsContext = &cy_capsense_tuner.sensorContext[28u],
        .ptrEltdConfig = &cy_capsense_electrodeConfig[28u],
        .ptrEltdCapacitance = NULL,
        .ptrSnsCapacitance = NULL,
        .ptrBslnInv = NULL,
        .ptrNoiseEnvelope = NULL,
        .ptrRawFilterHistory = NULL,
        .ptrRawFilterHistoryLow = NULL,
        .iirCoeff = 128u,
        .ptrDebounceArr = &cy_capsense_debounce[3u],
        .ptrDiplexTable = NULL,
        .centroidConfig = 1u,
        .xResolution = 100u,
        .yResolution = 0u,
        .numSns = 8u,
        .numCols = 8u,
        .numRows = 0u,
        .ptrPosFilterHistory = NULL,
        .ptrCsxTouchHistory = NULL,
        .ptrCsxTouchBuffer = NULL,
        .ptrCsdTouchBuffer = NULL,
        .ptrGestureConfig = NULL,
        .ptrGestureContext = NULL,
        .ballisticConfig = {
            .accelCoeff = 9u,
            .speedCoeff = 2u,
            .divisorValue = 4u,
            .speedThresholdX = 3u,
            .speedThresholdY = 4u,
        },
        .ptrBallisticContext = NULL,
        .aiirConfig = {
            .maxK = 60u,
            .minK = 1u,
            .noMovTh = 3u,
            .littleMovTh = 7u,
            .largeMovTh = 12u,
            .divVal = 64u,
        },
        .advConfig = {
            .penultimateTh = 100u,
            .virtualSnsTh = 100u,
            .crossCouplingTh = 5u,
        },
        .posFilterConfig = 0u,
        .rawFilterConfig = 0u,
        .senseMethod = CY_CAPSENSE_CSD_GROUP,
        .wdType = (uint8_t)CY_CAPSENSE_WD_LINEAR_SLIDER_E,
        .ptrMptxTable = NULL,
        .firstSlotId = 14u,
        .numSlots = 8u,
        .numChopCycles = 1u,
        .mptxOrder = 1u,
        .lfsrDitherLimit = 10u,
        .snsClkSourceAutoSelMode = CY_CAPSENSE_SNS_CLK_SOURCE_AUTO_SEL_MODE_STRONG,
        .mfsConfig = 0u,
    },
};

cy_stc_capsense_tuner_t cy_capsense_tuner =
{
    .commonContext = {
        #if (CY_CAPSENSE_MW_VERSION < 300)
            .configId = 0x0b98,
        #else
            .configId = 0x0b99,
        #endif

        .tunerCmd = 0u,
        .scanCounter = 0u,
        .tunerSt = 0u,
        .initDone = 0u,
        .status = 0u,
        .timestampInterval = 1u,
        .timestamp = 0u,
        .tunerCnt = 0u,
        .numFineInitCycles = 3u,
        .numFineInitWaitCycles = 15u,
        .lfsrPoly = 2124u,
        .lfsrScale = 0u,
        .cdacDitherSeed = 0u,
        .cdacDitherPoly = 0u,
        .modClk = 1u,
    },
    .widgetContext = {
        { /* Button0 */
            .fingerCap = 160u,
            .sigPFC = 0u,
            .maxRawCount = 0u,
            #if (CY_CAPSENSE_MW_VERSION >= 300)
                .maxRawCountRow = 0u,
            #endif
            .fingerTh = 100u,
            .proxTh = 200u,
            .lowBslnRst = 30u,
            .snsClk = 76u,
            .rowSnsClk = 76u,
            .gestureDetected = 0u,
            .gestureDirection = 0u,
            .xDelta = 0,
            .yDelta = 0,
            .noiseTh = 40u,
            .nNoiseTh = 40u,
            .hysteresis = 10u,
            .onDebounce = 3u,
            .snsClkSource = CY_CAPSENSE_CLK_SOURCE_DIRECT,
            .bslnCoeff = 1u,
            .status = 0u,
            .wdTouch = {
                .ptrPosition = NULL,
                .numPosition = 0,
            },
            .numSubConversions = 200u,
            .cdacRef = 18u,
            .rowCdacRef = 18u,
            .cicRate = 1u,
            .cdacDitherEn = 1u,
            .cdacDitherValue = 0u,
            .coarseInitBypassEn = 0u,
            .cdacCompDivider = 19u,
            .lfsrBits = CY_CAPSENSE_LFSR_BITS_AUTO,
        },
        { /* Button1 */
            .fingerCap = 160u,
            .sigPFC = 0u,
            .maxRawCount = 0u,
            #if (CY_CAPSENSE_MW_VERSION >= 300)
                .maxRawCountRow = 0u,
            #endif
            .fingerTh = 100u,
            .proxTh = 200u,
            .lowBslnRst = 30u,
            .snsClk = 76u,
            .rowSnsClk = 76u,
            .gestureDetected = 0u,
            .gestureDirection = 0u,
            .xDelta = 0,
            .yDelta = 0,
            .noiseTh = 40u,
            .nNoiseTh = 40u,
            .hysteresis = 10u,
            .onDebounce = 3u,
            .snsClkSource = CY_CAPSENSE_CLK_SOURCE_DIRECT,
            .bslnCoeff = 1u,
            .status = 0u,
            .wdTouch = {
                .ptrPosition = NULL,
                .numPosition = 0,
            },
            .numSubConversions = 200u,
            .cdacRef = 22u,
            .rowCdacRef = 22u,
            .cicRate = 1u,
            .cdacDitherEn = 1u,
            .cdacDitherValue = 0u,
            .coarseInitBypassEn = 0u,
            .cdacCompDivider = 19u,
            .lfsrBits = CY_CAPSENSE_LFSR_BITS_AUTO,
        },
        { /* Touchpad0 */
            .fingerCap = 160u,
            .sigPFC = 0u,
            .maxRawCount = 0u,
            #if (CY_CAPSENSE_MW_VERSION >= 300)
                .maxRawCountRow = 0u,
            #endif
            .fingerTh = 40u,
            .proxTh = 200u,
            .lowBslnRst = 30u,
            .snsClk = 68u,
            .rowSnsClk = 48u,
            .gestureDetected = 0u,
            .gestureDirection = 0u,
            .xDelta = 0,
            .yDelta = 0,
            .noiseTh = 20u,
            .nNoiseTh = 20u,
            .hysteresis = 5u,
            .onDebounce = 3u,
            .snsClkSource = CY_CAPSENSE_CLK_SOURCE_DIRECT,
            .bslnCoeff = 1u,
            .status = 0u,
            .wdTouch = {
                .ptrPosition = &cy_capsense_tuner.position[0u],
                .numPosition = 2,
            },
            .numSubConversions = 110u,
            .cdacRef = 32u,
            .rowCdacRef = 32u,
            .cicRate = 1u,
            .cdacDitherEn = 1u,
            .cdacDitherValue = 0u,
            .coarseInitBypassEn = 0u,
            .cdacCompDivider = 4u,
            .lfsrBits = CY_CAPSENSE_LFSR_BITS_AUTO,
        },
        { /* LinearSlider0 */
            .fingerCap = 160u,
            .sigPFC = 0u,
            .maxRawCount = 0u,
            #if (CY_CAPSENSE_MW_VERSION >= 300)
                .maxRawCountRow = 0u,
            #endif
            .fingerTh = 42u,
            .proxTh = 200u,
            .lowBslnRst = 30u,
            .snsClk = 44u,
            .rowSnsClk = 44u,
            .gestureDetected = 0u,
            .gestureDirection = 0u,
            .xDelta = 0,
            .yDelta = 0,
            .noiseTh = 12u,
            .nNoiseTh = 12u,
            .hysteresis = 5u,
            .onDebounce = 3u,
            .snsClkSource = CY_CAPSENSE_CLK_SOURCE_DIRECT,
            .bslnCoeff = 1u,
            .status = 0u,
            .wdTouch = {
                .ptrPosition = &cy_capsense_tuner.position[2u],
                .numPosition = 1,
            },
            .numSubConversions = 120u,
            .cdacRef = 24u,
            .rowCdacRef = 24u,
            .cicRate = 1u,
            .cdacDitherEn = 1u,
            .cdacDitherValue = 0u,
            .coarseInitBypassEn = 0u,
            .cdacCompDivider = 22u,
            .lfsrBits = CY_CAPSENSE_LFSR_BITS_AUTO,
        },
    },
    .sensorContext = {
        { /* Button0_Sns0 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 140u,
        },
        { /* Button1_Sns0 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 168u,
        },
        { /* Touchpad0_Col0 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 1u,
        },
        { /* Touchpad0_Col1 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 1u,
        },
        { /* Touchpad0_Col2 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 1u,
        },
        { /* Touchpad0_Col3 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 1u,
        },
        { /* Touchpad0_Col4 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 1u,
        },
        { /* Touchpad0_Col5 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 1u,
        },
        { /* Touchpad0_Col6 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 1u,
        },
        { /* Touchpad0_Col7 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 1u,
        },
        { /* Touchpad0_Col8 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 53u,
        },
        { /* Touchpad0_Col9 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 1u,
        },
        { /* Touchpad0_Col10 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 1u,
        },
        { /* Touchpad0_Col11 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 1u,
        },
        { /* Touchpad0_Col12 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 1u,
        },
        { /* Touchpad0_Col13 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 1u,
        },
        { /* Touchpad0_Col14 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 1u,
        },
        { /* Touchpad0_Col15 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 1u,
        },
        { /* Touchpad0_Row0 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 1u,
        },
        { /* Touchpad0_Row1 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 1u,
        },
        { /* Touchpad0_Row2 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 1u,
        },
        { /* Touchpad0_Row3 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 1u,
        },
        { /* Touchpad0_Row4 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 1u,
        },
        { /* Touchpad0_Row5 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 4u,
        },
        { /* Touchpad0_Row6 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 1u,
        },
        { /* Touchpad0_Row7 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 1u,
        },
        { /* Touchpad0_Row8 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 2u,
        },
        { /* Touchpad0_Row9 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 14u,
        },
        { /* LinearSlider0_Sns0 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 133u,
        },
        { /* LinearSlider0_Sns1 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 70u,
        },
        { /* LinearSlider0_Sns2 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 77u,
        },
        { /* LinearSlider0_Sns3 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 125u,
        },
        { /* LinearSlider0_Sns4 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 197u,
        },
        { /* LinearSlider0_Sns5 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 153u,
        },
        { /* LinearSlider0_Sns6 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 179u,
        },
        { /* LinearSlider0_Sns7 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 222u,
        },
    },
    .position = {
        { /* Touchpad0 */
            .x = 0u,
            .y = 0u,
            .z = 0u,
            .id = 0u,
        },
        { /* Touchpad0 */
            .x = 0u,
            .y = 0u,
            .z = 0u,
            .id = 0u,
        },
        { /* LinearSlider0 */
            .x = 0u,
            .y = 0u,
            .z = 0u,
            .id = 0u,
        },
    },
};

#if (CY_CAPSENSE_BIST_EN != 0)
cy_stc_capsense_bist_context_t cy_capsense_bist_context =
{
};
#endif

cy_stc_capsense_context_t cy_capsense_context =
{
    .ptrCommonConfig = &cy_capsense_commonConfig,
    .ptrCommonContext = &cy_capsense_tuner.commonContext,
    .ptrInternalContext = &cy_capsense_internalContext,
    .ptrWdConfig = &cy_capsense_widgetConfig[0u],
    .ptrWdContext = &cy_capsense_tuner.widgetContext[0u],
    .ptrPinConfig = &cy_capsense_pinConfig[0u],
    .ptrShieldPinConfig = &cy_capsense_shieldPinConfig[0u],
    .ptrActiveScanSns = &cy_capsense_activeScanSns[0u],
    .ptrBistContext = NULL,
    .ptrBaseFrameContext = &cy_capsense_baseFrame[0],
    .ptrSensorFrameContext = &cy_capsense_sensorFrameContext[0],
    .ptrScanSlots = &cy_capsense_scanSlots[0],
};

#endif /* CY_CAPSENSE_CORE == __CORTEX_M */

#endif /* !defined(CY_DISABLE_CAPSENSE) */

/* [] END OF FILE */
