/*******************************************************************************
* File Name: cycfg_capsense.c
* Version: 3.20
*
* Description:
* CapSense Middleware configuration
* This file should not be modified. It was automatically generated by
* CapSense Configurator 3.20.0.3518
*
********************************************************************************
* Copyright 2020 Cypress Semiconductor Corporation
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#include "cycfg_capsense.h"

#if !defined(CY_DISABLE_CAPSENSE)

#if (CY_CAPSENSE_CORE == __CORTEX_M)

#ifndef CSD_CMODPADS_PORT
#define CSD_CMODPADS_PORT 0xFF
#endif
#ifndef CSD_CMODPADS_PIN
#define CSD_CMODPADS_PIN 0xFF
#endif
#ifndef CSD_CSH_TANKPADS_PORT
#define CSD_CSH_TANKPADS_PORT 0xFF
#endif
#ifndef CSD_CSH_TANKPADS_PIN
#define CSD_CSH_TANKPADS_PIN 0xFF
#endif
#ifndef CSD_CSHIELDPADS_PORT
#define CSD_CSHIELDPADS_PORT 0xFF
#endif
#ifndef CSD_CSHIELDPADS_PIN
#define CSD_CSHIELDPADS_PIN 0xFF
#endif
#ifndef CSD_VREF_EXT_PORT
#define CSD_VREF_EXT_PORT 0xFF
#endif
#ifndef CSD_VREF_EXT_PIN
#define CSD_VREF_EXT_PIN 0xFF
#endif

#define CY_CAPSENSE_WIDGET_COUNT                                                 (2u)
#define CY_CAPSENSE_SENSOR_COUNT                                                 (2u)
#define CY_CAPSENSE_ELTD_COUNT                                                   (4u)
#define CY_CAPSENSE_PIN_COUNT                                                    (3u)
#define CY_CAPSENSE_SHIELD_PIN_COUNT                                             (0u)
#define CY_CAPSENSE_POSITION_SIZE                                                (0u)
#define CY_CAPSENSE_DEBOUNCE_SIZE                                                (2u)
#define CY_CAPSENSE_NOISE_ENVELOPE_SIZE                                          (0u)
#define CY_CAPSENSE_RAW_HISTORY_SIZE                                             (0u)
#define CY_CAPSENSE_IIR_HISTORY_LOW_SIZE                                         (0u)
#define CY_CAPSENSE_POSITION_FILTER_HISTORY_SIZE                                 (0u)
#define CY_CAPSENSE_TOUCH_FILTER_HISTORY_SIZE                                    (0u)
#define CY_CAPSENSE_DIPLEX_SIZE                                                  (0u)
#define CY_CAPSENSE_CSD_TOUCHPAD_MAX_SENSORS_SIZE                                (0u)
#define CY_CAPSENSE_CSX_TOUCH_BUFFER_ENABLE                                      (0u)
#define CY_CAPSENSE_CSX_TOUCH_HISTORY_SIZE                                       (0u)
#define CY_CAPSENSE_BALLISTIC_WIDGET_COUNT                                       (0u)
#define CY_CAPSENSE_GESTURE_WIDGET_COUNT                                         (0u)
#define CY_CAPSENSE_TOTAL_CH_NUMBER                                              (2u)
#define CY_CAPSENSE_SLOT_COUNT                                                   (2u)
#define CY_CAPSENSE_SENSOR_CONNECTION_MODE_LEGACY                                (1u)
#define CY_CAPSENSE_SENSOR_FRAME_SIZE                                            (5u)
#define CY_CAPSENSE_MULTI_PHASE_ENABLED                                          (0u)
#define CY_CAPSENSE_MPTX_WIDGET_NUMBER                                           (0u)

static cy_stc_capsense_internal_context_t cy_capsense_internalContext;
static cy_stc_active_scan_sns_t cy_capsense_activeScanSns[CY_MSC_ENABLED_CH_NUMBER];

static cy_stc_msc_base_config_t cy_capsense_baseFrame[CY_MSC_ENABLED_CH_NUMBER];

#if (CY_CAPSENSE_SENSOR_CONNECTION_MODE_LEGACY == 0)
    static uint32_t cy_capsense_sensorFrameContext[CY_CAPSENSE_SENSOR_FRAME_SIZE * CY_CAPSENSE_SLOT_COUNT * CY_CAPSENSE_TOTAL_CH_NUMBER];
#endif

#if (CY_CAPSENSE_DEBOUNCE_SIZE > 0)
    static uint8_t cy_capsense_debounce[CY_CAPSENSE_DEBOUNCE_SIZE] = {0};
#endif

#if (CY_CAPSENSE_NOISE_ENVELOPE_SIZE > 0)
    static cy_stc_capsense_smartsense_csd_noise_envelope_t cy_capsense_noiseEnvelope[CY_CAPSENSE_NOISE_ENVELOPE_SIZE];
#endif

#if (CY_CAPSENSE_RAW_HISTORY_SIZE > 0)
    static uint16_t cy_capsense_rawFilterHistory[CY_CAPSENSE_RAW_HISTORY_SIZE] = {0};
#endif

#if (CY_CAPSENSE_IIR_HISTORY_LOW_SIZE > 0)
    static uint8_t cy_capsense_iirHistoryLow[CY_CAPSENSE_IIR_HISTORY_LOW_SIZE] = {0};
#endif

#if (CY_CAPSENSE_POSITION_FILTER_HISTORY_SIZE > 0)
    static cy_stc_capsense_position_t cy_capsense_positionFilterHistory[CY_CAPSENSE_POSITION_FILTER_HISTORY_SIZE];
#endif

#if (CY_CAPSENSE_TOUCH_FILTER_HISTORY_SIZE > 0)
    static cy_stc_capsense_touch_t cy_capsense_touchFilterHistory[CY_CAPSENSE_TOUCH_FILTER_HISTORY_SIZE] =
    {
    };
#endif

#if (CY_CAPSENSE_DIPLEX_SIZE > 0)
    static const uint8_t cy_capsense_diplexTable[CY_CAPSENSE_DIPLEX_SIZE] =
    {
    };
#endif

#if (CY_CAPSENSE_CSD_TOUCHPAD_MAX_SENSORS_SIZE > 0)
    static uint16_t cy_capsense_csdTouchBuffer[CY_CAPSENSE_CSD_TOUCHPAD_MAX_SENSORS_SIZE] = {0};
#endif

#if (CY_CAPSENSE_CSX_TOUCH_BUFFER_ENABLE > 0)
    static cy_stc_capsense_csx_touch_buffer_t cy_capsense_csxTouchBuffer;
#endif

#if (CY_CAPSENSE_CSX_TOUCH_HISTORY_SIZE > 0)
    static cy_stc_capsense_csx_touch_history_t cy_capsense_csxTouchHistory[CY_CAPSENSE_CSX_TOUCH_HISTORY_SIZE] =
    {
    };
#endif

#if (CY_CAPSENSE_BALLISTIC_WIDGET_COUNT > 0)
    static cy_stc_capsense_ballistic_context_t cy_capsense_ballisticContext[CY_CAPSENSE_BALLISTIC_WIDGET_COUNT];
#endif

#if (CY_CAPSENSE_GESTURE_WIDGET_COUNT > 0)
    static cy_stc_capsense_gesture_context_t cy_capsense_gestureContext[CY_CAPSENSE_GESTURE_WIDGET_COUNT];
#endif

static cy_stc_msc_channel_config_t cy_capsense_msc_ch_config[CY_MSC_CH_NUMBER] =
{
    {   /* MSC channel 0 */
        .ptrMscBase = CY_MSC0_HW,
        .ptrMscContext = &cy_msc_0_context,
        .portCmod1 = CY_MSC0_Cmod1_PORT,
        .pinCmod1 = CY_MSC0_Cmod1_PIN,
        .portCmod2 = CY_MSC0_Cmod2_PORT,
        .pinCmod2 = CY_MSC0_Cmod2_PIN,
        .dmaWrChIndex = 0u,
        .dmaChainWrChIndex = 0u,
        .dmaRdChIndex = 0u,
        .dmaChainRdChIndex = 0u,
    },
    {   /* MSC channel 1 */
        .ptrMscBase = CY_MSC1_HW,
        .ptrMscContext = &cy_msc_1_context,
        .portCmod1 = CY_MSC1_Cmod1_PORT,
        .pinCmod1 = CY_MSC1_Cmod1_PIN,
        .portCmod2 = CY_MSC1_Cmod2_PORT,
        .pinCmod2 = CY_MSC1_Cmod2_PIN,
        .dmaWrChIndex = 0u,
        .dmaChainWrChIndex = 0u,
        .dmaRdChIndex = 0u,
        .dmaChainRdChIndex = 0u,
    },
};

static cy_stc_capsense_scan_slot_t cy_capsense_scanSlots[CY_CAPSENSE_SLOT_COUNT * CY_CAPSENSE_TOTAL_CH_NUMBER] =
{
    /* Channel 0 */
    {   /* Slot 0 */
        0xFFFEu,
        1u
    },
    {   /* Slot 1 */
        0xFFFFu,
        0xFFFFu
    },
    /* Channel 1 */
    {   /* Slot 0 */
        CY_CAPSENSE_BUTTON0_WDGT_ID,
        CY_CAPSENSE_BUTTON0_SNS0_ID
    },
    {   /* Slot 1 */
        CY_CAPSENSE_BUTTON1_WDGT_ID,
        CY_CAPSENSE_BUTTON1_SNS0_ID
    },
};

#if ((CY_CAPSENSE_DMA_CONFIGURED != 0) && (CY_CAPSENSE_SENSOR_CONNECTION_MODE_LEGACY == 0))
static const uint32_t *ptrDmaWrChSnsConfigs[CY_CAPSENSE_SENSOR_COUNT] = {
    &cy_capsense_sensorFrameContext[0u],
    &cy_capsense_sensorFrameContext[5u],
};
static const uint16_t *ptrDmaRdChSnsConfigs[CY_CAPSENSE_SENSOR_COUNT] = {
    &cy_capsense_tuner.sensorContext[0u].raw,
    &cy_capsense_tuner.sensorContext[1u].raw,
};
#endif

static const cy_stc_capsense_common_config_t cy_capsense_commonConfig =
{
    .cpuClkHz = CY_CAPSENSE_CPU_CLK,
    .periClkHz = CY_CAPSENSE_PERI_CLK,
    .vdda = CY_CAPSENSE_VDDA_MV,
    .numPin = CY_CAPSENSE_PIN_COUNT,
    .numSns = CY_CAPSENSE_SENSOR_COUNT,
    .numWd = CY_CAPSENSE_WIDGET_COUNT,
    .csdEn = CY_CAPSENSE_DISABLE,
    .csxEn = CY_CAPSENSE_ENABLE,
    .mfsEn = CY_CAPSENSE_DISABLE,
    .bistEn = CY_CAPSENSE_DISABLE,
    .positionFilterEn = CY_CAPSENSE_DISABLE,
    .periDividerType = CY_CAPSENSE_PERI_DIV_TYPE,
    .periDividerIndex = CY_CAPSENSE_PERI_DIV_INDEX,
    .analogWakeupDelay = 10u,
    .proxTouchCoeff = 300u,
    .swSensorAutoResetEn = CY_CAPSENSE_DISABLE,
    .csdInactiveSnsConnection = CY_CAPSENSE_SNS_CONNECTION_GROUND,
    .csdRConst = 1000u,
    .csdShieldNumPin = 0u,
    .csdRawTarget = 85u,
    .csdAutotuneEn = CY_CAPSENSE_CSD_SS_DIS,
    .csdCalibrationError = 10u,
    .csdMfsDividerOffsetF1 = 1u,
    .csdMfsDividerOffsetF2 = 2u,
    .csxRawTarget = 40u,
    .csxCalibrationError = 20u,
    .csxMfsDividerOffsetF1 = 1u,
    .csxMfsDividerOffsetF2 = 2u,
    .ptrMscChConfig = &cy_capsense_msc_ch_config[0u],
#if ((CY_CAPSENSE_DMA_CONFIGURED != 0) && (CY_CAPSENSE_SENSOR_CONNECTION_MODE_LEGACY == 0))
    .ptrDmacBase = DMAC,
    .ptrDmaWrChSnsCfgAddr = ptrDmaWrChSnsConfigs,
    .ptrDmaRdChSnsCfgAddr = ptrDmaRdChSnsConfigs,
#endif
    .csdShieldMode = CY_CAPSENSE_SHIELD_DISABLED,
    .sensorConnection = CY_CAPSENSE_AMUX_SENSOR_CONNECTION_METHOD,
    .csdCdacAutocalEn = CY_CAPSENSE_DISABLE,
    .csdCdacCompEn = CY_CAPSENSE_DISABLE,
    .csxCdacAutocalEn = CY_CAPSENSE_ENABLE,
    .csxCdacCompEn = CY_CAPSENSE_DISABLE,
    .csxAutotuneEn = CY_CAPSENSE_CSD_SS_DIS,
    .scanningMode = CY_CAPSENSE_SCAN_MODE_INT_DRIVEN,
    .mptxEn = CY_CAPSENSE_DISABLE,
    .numEpiCycles = 20u,
    .chopPolarity = CY_CAPSENSE_DISABLE,
    .numCoarseInitChargeCycles = 60u,
    .numCoarseInitSettleCycles = 60u,
    .cicFilterMode = CY_CAPSENSE_CIC_FILTER,
    .numBadScans = 0u,
    .counterMode = CY_CAPSENSE_COUNTER_MODE_SATURATE,
    .syncFrameStartEn = CY_CAPSENSE_DISABLE,
    .syncClockEn = CY_CAPSENSE_DISABLE,
    .syncMode = CY_CAPSENSE_SYNC_INTERNAL,
    .numChips = 1u,
    .numChannels = CY_MSC_ENABLED_CH_NUMBER,
    .numSlots = CY_CAPSENSE_SLOT_COUNT,
    .channelOffset = CY_MSC_CHANNEL_OFFSET,
};

static const cy_stc_capsense_fptr_config_t cy_capsense_fptrConfig =
{
    .fptrCSDSetupWidget = NULL,
    .fptrCSDScan = NULL,
    .fptrCSDDisableMode = NULL,
    .fptrCSDInitialize = NULL,
        
#if (CY_CAPSENSE_CSD_EN == 0)
    .fptrDpProcessCsdWidgetRawCounts = NULL,
    .fptrDpProcessCsdWidgetStatus = NULL,
#else
    .fptrDpProcessCsdWidgetRawCounts = &Cy_CapSense_DpProcessCsdWidgetRawCounts,
    .fptrDpProcessCsdWidgetStatus = &Cy_CapSense_DpProcessCsdWidgetStatus,
#endif

    .fptrCSDScanISR = NULL,

    .fptrCSXSetupWidget = NULL,
    .fptrCSXScan = NULL,
    .fptrCSXDisableMode = NULL,
    .fptrCSXInitialize = NULL,
    
#if (CY_CAPSENSE_CSX_EN == 0)
    .fptrDpProcessCsxWidgetRawCounts = NULL,
    .fptrDpProcessCsxWidgetStatus = NULL,
#else
    .fptrDpProcessCsxWidgetRawCounts = &Cy_CapSense_DpProcessCsxWidgetRawCounts,
    .fptrDpProcessCsxWidgetStatus = &Cy_CapSense_DpProcessCsxWidgetStatus,
#endif

    .fptrCSXScanISR = NULL,

#if (CY_CAPSENSE_ADAPTIVE_FILTER_EN == 0)
    .fptrAdaptiveFilterInitializeLib = NULL,
    .fptrAdaptiveFilterRunLib = NULL,
#else
    .fptrAdaptiveFilterInitializeLib = &Cy_CapSense_AdaptiveFilterInitialize_Lib,
    .fptrAdaptiveFilterRunLib = &Cy_CapSense_AdaptiveFilterRun_Lib,
#endif

#if (CY_CAPSENSE_BALLISTIC_MULTIPLIER_EN == 0)
    .fptrBallisticMultiplierLib = NULL,
#else
    .fptrBallisticMultiplierLib = &Cy_CapSense_BallisticMultiplier_Lib,
#endif

#if (CY_CAPSENSE_RAWCOUNT_FILTER_EN == 0)
    .fptrInitializeAllFilters = NULL,
    .fptrFtRunEnabledFiltersInternal = NULL,
#else
    .fptrInitializeAllFilters = &Cy_CapSense_InitializeAllFilters,
    .fptrFtRunEnabledFiltersInternal = &Cy_CapSense_FtRunEnabledFiltersInternal,
#endif

#if (CY_CAPSENSE_CSD_POSITION_FILTER_EN == 0)
    .fptrProcessPositionFilters = NULL,
#else
    .fptrProcessPositionFilters = &Cy_CapSense_ProcessPositionFilters,
#endif

#if ((CY_CAPSENSE_CSX_POSITION_FILTER_EN == 0) && (CY_CAPSENSE_CSD_POSITION_FILTER_EN == 0))
    .fptrRunPositionFilters = NULL,
    .fptrInitPositionFilters = NULL,
#else
    .fptrRunPositionFilters = &Cy_CapSense_RunPositionFilters,
    .fptrInitPositionFilters = &Cy_CapSense_InitPositionFilters,
#endif

#if ((CY_CAPSENSE_CSD_BUTTON_EN == 0) && \
     (CY_CAPSENSE_CSX_BUTTON_EN == 0) && (CY_CAPSENSE_CSX_MATRIX_EN == 0))
    .fptrDpProcessButton = NULL,
#else
    .fptrDpProcessButton = &Cy_CapSense_DpProcessButton,
#endif

#if (CY_CAPSENSE_CSD_SLIDER_EN == 0)
    .fptrDpProcessSlider = NULL,
#else
    .fptrDpProcessSlider = &Cy_CapSense_DpProcessSlider,
#endif

#if (CY_CAPSENSE_CSD_MATRIX_EN == 0)
    .fptrDpProcessCsdMatrix = NULL,
#else
    .fptrDpProcessCsdMatrix = &Cy_CapSense_DpProcessCsdMatrix,
#endif

#if (CY_CAPSENSE_CSD_TOUCHPAD_EN == 0)
    .fptrDpProcessCsdTouchpad = NULL,
#else
    .fptrDpProcessCsdTouchpad = &Cy_CapSense_DpProcessCsdTouchpad,
#endif

#if (CY_CAPSENSE_CSD_PROXIMITY_EN == 0)
    .fptrDpProcessProximity = NULL,
#else
    .fptrDpProcessProximity = &Cy_CapSense_DpProcessProximity,
#endif

#if (CY_CAPSENSE_CSX_TOUCHPAD_EN == 0)
    .fptrDpProcessCsxTouchpad = NULL,
#else
    .fptrDpProcessCsxTouchpad = &Cy_CapSense_DpProcessCsxTouchpad,
#endif

#if (CY_CAPSENSE_ADVANCED_CENTROID_5X5_EN == 0)
    .fptrDpAdvancedCentroidTouchpad = NULL,
#else
    .fptrDpAdvancedCentroidTouchpad = &Cy_CapSense_DpAdvancedCentroidTouchpad,
#endif

    .fptrCSDCalibrateWidget = NULL,
    .fptrCalibrateAllCsdWidgets = NULL,
    .fptrCalibrateAllCsxWidgets = NULL,
    
    .fptrRunNoiseEnvelopeLib = NULL,
    .fptrInitializeNoiseEnvelopeLib = NULL,

#if (CY_CAPSENSE_SMARTSENSE_FULL_EN == 0)
    .fptrDpUpdateThresholds = NULL,
#else
    .fptrDpUpdateThresholds = &Cy_CapSense_DpUpdateThresholds,
#endif

    .fptrSsAutoTune = NULL,

    .fptrBistInitialize = NULL,
    .fptrBistDisableMode = NULL,
    .fptrBistDsInitialize = NULL,
};

#if (CY_CAPSENSE_MULTI_PHASE_ENABLED)
    static cy_stc_capsense_mptx_table_t cy_capsense_mptx_table[CY_CAPSENSE_MPTX_WIDGET_NUMBER] =
    {
    };
#endif

static const cy_stc_capsense_pin_config_t cy_capsense_pinConfig[CY_CAPSENSE_PIN_COUNT] =
{
    { /* Button0_Rx0 */
        Button0_Rx0_PORT,
        Button0_Rx0_PIN,
        0u,
        1u,
    },
    { /* Button0_Tx */
        Button0_Tx_PORT,
        Button0_Tx_PIN,
        0u,
        0u,
    },
    { /* Button1_Tx */
        Button1_Tx_PORT,
        Button1_Tx_PIN,
        0u,
        1u,
    },
};

#if (CY_CAPSENSE_SHIELD_PIN_COUNT > 0)
    static const cy_stc_capsense_pin_config_t cy_capsense_shieldPinConfig[CY_CAPSENSE_SHIELD_PIN_COUNT] =
    {
    };
#endif

static const cy_stc_capsense_electrode_config_t cy_capsense_electrodeConfig[CY_CAPSENSE_ELTD_COUNT] =
{
    { /* Button0_Rx0 */
        .ptrPin = &cy_capsense_pinConfig[0u],
        .type = 0u,
        .numPins = 1u,
        .chId = 1u,
    },
    { /* Button0_Tx */
        .ptrPin = &cy_capsense_pinConfig[1u],
        .type = 0u,
        .numPins = 1u,
        .chId = 0u,
    },
    { /* Button1_Rx0 */
        .ptrPin = &cy_capsense_pinConfig[0u],
        .type = 0u,
        .numPins = 1u,
        .chId = 1u,
    },
    { /* Button1_Tx */
        .ptrPin = &cy_capsense_pinConfig[2u],
        .type = 0u,
        .numPins = 1u,
        .chId = 1u,
    },
};

static const cy_stc_capsense_widget_config_t cy_capsense_widgetConfig[CY_CAPSENSE_WIDGET_COUNT] =
{
    { /* Button0 */
        .ptrWdContext = &cy_capsense_tuner.widgetContext[0u],
        .ptrSnsContext = &cy_capsense_tuner.sensorContext[0u],
        .ptrEltdConfig = &cy_capsense_electrodeConfig[0u],
#if (CY_CAPSENSE_BIST_SUPPORTED)
        .ptrEltdCapacitance = NULL,
        .ptrBslnInv = NULL,
#endif
        .ptrNoiseEnvelope = NULL,
        .ptrRawFilterHistory = NULL,
        .ptrRawFilterHistoryLow = NULL,
        .iirCoeff = 128u,
        .ptrDebounceArr = &cy_capsense_debounce[0u],
        .ptrDiplexTable = NULL,
        .centroidConfig = 0u,
        .xResolution = 0u,
        .yResolution = 0u,
        .numSns = 1u,
        .numCols = 1u,
        .numRows = 1u,
        .ptrPosFilterHistory = NULL,
        .ptrCsxTouchHistory = NULL,
        .ptrCsxTouchBuffer = NULL,
        .ptrCsdTouchBuffer = NULL,
        .ptrGestureConfig = NULL,
        .ptrGestureContext = NULL,
        .ballisticConfig = {
            .accelCoeff = 9u,
            .speedCoeff = 2u,
            .divisorValue = 4u,
            .speedThresholdX = 3u,
            .speedThresholdY = 4u,
        },
        .ptrBallisticContext = NULL,
        .aiirConfig = {
            .maxK = 60u,
            .minK = 1u,
            .noMovTh = 3u,
            .littleMovTh = 7u,
            .largeMovTh = 12u,
            .divVal = 64u,
        },
        .advConfig = {
            .penultimateTh = 100u,
            .virtualSnsTh = 100u,
            .crossCouplingTh = 5u,
        },
        .posFilterConfig = 0u,
        .rawFilterConfig = 0u,
        .senseMethod = CY_CAPSENSE_CSX_RM_SENSING_METHOD,
        .wdType = CY_CAPSENSE_WD_BUTTON_E,
        .senseGroup = CY_CAPSENSE_CSX_GROUP,
        .ptrMptxTable = NULL,
        .firstSlotId = 0u,
        .numSlots = 1u,
        .numChopCycles = 1u,
        .mptxOrder = 1u,
    },
    { /* Button1 */
        .ptrWdContext = &cy_capsense_tuner.widgetContext[1u],
        .ptrSnsContext = &cy_capsense_tuner.sensorContext[1u],
        .ptrEltdConfig = &cy_capsense_electrodeConfig[2u],
#if (CY_CAPSENSE_BIST_SUPPORTED)
        .ptrEltdCapacitance = NULL,
        .ptrBslnInv = NULL,
#endif
        .ptrNoiseEnvelope = NULL,
        .ptrRawFilterHistory = NULL,
        .ptrRawFilterHistoryLow = NULL,
        .iirCoeff = 128u,
        .ptrDebounceArr = &cy_capsense_debounce[1u],
        .ptrDiplexTable = NULL,
        .centroidConfig = 0u,
        .xResolution = 0u,
        .yResolution = 0u,
        .numSns = 1u,
        .numCols = 1u,
        .numRows = 1u,
        .ptrPosFilterHistory = NULL,
        .ptrCsxTouchHistory = NULL,
        .ptrCsxTouchBuffer = NULL,
        .ptrCsdTouchBuffer = NULL,
        .ptrGestureConfig = NULL,
        .ptrGestureContext = NULL,
        .ballisticConfig = {
            .accelCoeff = 9u,
            .speedCoeff = 2u,
            .divisorValue = 4u,
            .speedThresholdX = 3u,
            .speedThresholdY = 4u,
        },
        .ptrBallisticContext = NULL,
        .aiirConfig = {
            .maxK = 60u,
            .minK = 1u,
            .noMovTh = 3u,
            .littleMovTh = 7u,
            .largeMovTh = 12u,
            .divVal = 64u,
        },
        .advConfig = {
            .penultimateTh = 100u,
            .virtualSnsTh = 100u,
            .crossCouplingTh = 5u,
        },
        .posFilterConfig = 0u,
        .rawFilterConfig = 0u,
        .senseMethod = CY_CAPSENSE_CSX_RM_SENSING_METHOD,
        .wdType = CY_CAPSENSE_WD_BUTTON_E,
        .senseGroup = CY_CAPSENSE_CSX_GROUP,
        .ptrMptxTable = NULL,
        .firstSlotId = 1u,
        .numSlots = 1u,
        .numChopCycles = 1u,
        .mptxOrder = 1u,
    },
};

cy_stc_capsense_tuner_t cy_capsense_tuner =
{
    .commonContext = {
        .configId = 0x3827,
        .tunerCmd = 0u,
        .scanCounter = 0u,
        .tunerSt = 0u,
        .initDone = 0u,
        .ptrSSCallback = NULL,
        .ptrEOSCallback = NULL,
        .ptrTunerSendCallback = NULL,
        .ptrTunerReceiveCallback = NULL,
        .status = 0u,
        .timestampInterval = 1u,
        .timestamp = 0u,
        .tunerCnt = 0u,
        .numFineInitCycles = 3u,
        .numFineInitWaitCycles = 15u,
        .lfsrPoly = 2124u,
        .lfsrScale = 0u,
        .cdacDitherSeed = 0u,
        .cdacDitherPoly = 0u,
        .modClk = 2u,
    },
    .widgetContext = {
        {
            .fingerCap = 160u,
            .sigPFC = 0u,
            .maxRawCount = 0u,
            .fingerTh = 64u,
            .proxTh = 200u,
            .lowBslnRst = 30u,
            .snsClk = 13u,
            .rowSnsClk = 4u,
            .gestureDetected = 0u,
            .gestureDirection = 0u,
            .xDelta = 0u,
            .yDelta = 0u,
            .noiseTh = 32u,
            .nNoiseTh = 32u,
            .hysteresis = 8u,
            .onDebounce = 3u,
            .snsClkSource = CY_CAPSENSE_CLK_SOURCE_DIRECT,
            .bslnCoeff = 1u,
            .status = 0u,
            .wdTouch = {
                .ptrPosition = NULL,
                .numPosition = 0,
            },
            .numSubConversions = 80u,
            .cdacRef = { 32u, 32u, 32u, },
            .rowCdacRef = { 32u, 32u, 32u, },
            .cicRate = 1u,
            .cdacDitherEn = 0u,
            .cdacDitherValue = 0u,
            .coarseInitBypassEn = 0u,
            .cdacCompDivider = 6u,
        },
        {
            .fingerCap = 160u,
            .sigPFC = 0u,
            .maxRawCount = 0u,
            .fingerTh = 64u,
            .proxTh = 200u,
            .lowBslnRst = 30u,
            .snsClk = 15u,
            .rowSnsClk = 4u,
            .gestureDetected = 0u,
            .gestureDirection = 0u,
            .xDelta = 0u,
            .yDelta = 0u,
            .noiseTh = 32u,
            .nNoiseTh = 32u,
            .hysteresis = 8u,
            .onDebounce = 3u,
            .snsClkSource = CY_CAPSENSE_CLK_SOURCE_DIRECT,
            .bslnCoeff = 1u,
            .status = 0u,
            .wdTouch = {
                .ptrPosition = NULL,
                .numPosition = 0,
            },
            .numSubConversions = 100u,
            .cdacRef = { 32u, 32u, 32u, },
            .rowCdacRef = { 32u, 32u, 32u, },
            .cicRate = 1u,
            .cdacDitherEn = 0u,
            .cdacDitherValue = 0u,
            .coarseInitBypassEn = 0u,
            .cdacCompDivider = 6u,
        },
    },
    .sensorContext = {
        {
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 0u,
        },
        {
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 0u,
        },
    },
};

#if (CY_CAPSENSE_BIST_SUPPORTED)
#if (CY_CAPSENSE_BIST_EN != 0)
#define CY_CAPSENSE_MULTI_FREQUENCY_COUNT                      (CY_CAPSENSE_MULTI_FREQUENCY_SCAN_EN == 0 ? 1 : 3)
uint16_t bslnInv[CY_CAPSENSE_SENSOR_COUNT * CY_CAPSENSE_MULTI_FREQUENCY_COUNT];
uint32_t eltdCap[CY_CAPSENSE_ELTD_COUNT];
uint16_t wdgtCrc[CY_CAPSENSE_WIDGET_COUNT];

cy_stc_capsense_bist_context_t cy_capsense_bist_context =
{
};
#endif
#endif

cy_stc_capsense_context_t cy_capsense_context =
{
    .ptrCommonConfig = &cy_capsense_commonConfig,
    .ptrCommonContext = &cy_capsense_tuner.commonContext,
    .ptrInternalContext = &cy_capsense_internalContext,
    .ptrWdConfig = &cy_capsense_widgetConfig[0u],
    .ptrWdContext = &cy_capsense_tuner.widgetContext[0u],
    .ptrPinConfig = &cy_capsense_pinConfig[0u],
    .ptrShieldPinConfig = NULL,
    .ptrActiveScanSns = &cy_capsense_activeScanSns[0u],
    .ptrFptrConfig = (const void *) &cy_capsense_fptrConfig,
#if (CY_CAPSENSE_BIST_SUPPORTED)
    .ptrBistContext = NULL,
#endif
    .ptrBaseFrameContext = &cy_capsense_baseFrame[0],
    .ptrSensorFrameContext = NULL,
    .ptrScanSlots = &cy_capsense_scanSlots[0],
};

#endif /* CY_CAPSENSE_CORE == __CORTEX_M */

#endif /* !defined(CY_DISABLE_CAPSENSE) */

/* [] END OF FILE */

